### ISSUE TITLE
Change of "DsmSvc" Service

### ISSUE THREAD

**Issue by Edocsyl** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#10]
Hello, i got Feedback from Test Users, that the network Printers are not showing up in Settings/Conrol Panel. I found out, that this Service is needed to make a Connection to the Printers and list them at these two configuration pages. 
Could you add this expirience to the Description of the Service? 

Regards, Kaj

` {
"Name": "DsmSvc",
"VDIState": "Disabled",
"Description": "Enables the detection, download and installation of device-related software. If this service is disabled, devices may be configured with outdated software, and may not work correctly. Network-Printers, for example, are not displayed in Settings -> Devices -> Printers & Scanner."
},`

**Comment by sandude-ms** [comment]
To close this issue, I am going to change the scripts by removing the entry for 'DsmSvc'.  I was on the fence with this one the last time I swept through the list.  The fact that I cannot find solid documentation tips me to leaving the service alone.  I will change that now and that will be in the scripts shortly.  Thank you for reporting this issue.
