### ISSUE TITLE
Newest version won't run. "The term 'BEGIN' is not recognized as the name "

### ISSUE THREAD

**Issue by stashgumbo** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#100]
What am I doing wrong?

PS C:\Optimize> .\Win10_VirtualDesktop_Optimize.ps1 -Verbose
BEGIN : The term 'BEGIN' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Optimize\Win10_VirtualDesktop_Optimize.ps1:84 char:1
+ BEGIN {
+ ~~~~~
    + CategoryInfo          : ObjectNotFound: (BEGIN:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

Get-Process : Cannot evaluate parameter 'Name' because its argument is specified as a script block and there is no
input. A script block cannot be evaluated without input.
At C:\Optimize\Win10_VirtualDesktop_Optimize.ps1:112 char:9
+ PROCESS {
+         ~
    + CategoryInfo          : MetadataError: (:) [Get-Process], ParameterBindingException
    + FullyQualifiedErrorId : ScriptBlockArgumentNoInput,Microsoft.PowerShell.Commands.GetProcessCommand

![image](https://user-images.githubusercontent.com/92749174/137780271-41f161ae-68f4-4925-874b-9f3def628afd.png)

**Comment by tmmuessig** [comment]
Happy to help.. Let us know if you have any more issues.

**Comment by tmmuessig** [comment]
You should be able to run the following on that box that needs Windows Media Player, though I have not 100% tested this so you might have to play around with it a little:

`Get-WindowsPackage -Online -PackageName "*Windows-MediaPlayer*" | Add-WindowsPackage -Online`
