### ISSUE TITLE
Error BEGIN is not recognized as a the name of a cmdlet, function, script file, or operable program.

### ISSUE THREAD

**Issue by DeXLLG** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#106]
Used this tool previously on older versions of Win10, but now seeing this error using the new Windows_VDOT.ps1 on Win10 21H1.

**Comment by tmmuessig** [comment]
Hi @DeXLLG - I just pulled down the Main branch and was not able to repo the error.  My guess is there is something on your copy before the "Begin" block that should not be there or there is a "{" or a "}" missing or out of place.  Can you please try with a fresh downloaded copy of the Main repo?

**Comment by tmmuessig** [comment]
@DeXLLG  - Did this resolve your issue?
