### ISSUE TITLE
Disabling of scheduled tasks fails when integrated with AIB/Packer

### ISSUE THREAD

**Issue by Lucero7919** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#108]
Error is 

```
Get-ScheduledTask : The system cannot find the file specified.
At C:\Optimise\Windows_VDOT.ps1:234 char:35
+ ...                   $TaskObject = Get-ScheduledTask $Item.ScheduledTask
```

Steps to re-produce. Seems to be inconsistent, but if using PoSH ISE or if run once with a user, then a second user logs in and runs again, script errors. Additionally, although not verified, after Sysprep, Tasks are enabled again

**Comment by tmmuessig** [comment]
Unable to repro, closing
