### ISSUE TITLE
Orphaned Start Menu items exist after provisioning

### ISSUE THREAD

**Issue by Lucero7919** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#109]
![image](https://user-images.githubusercontent.com/41423820/153596938-2407af25-91ce-4057-a1c8-5f756243e105.png)
These remain after provisioning a machine with VDOT

**Comment by davetustin** [comment]
Hi @Lucero7919 

If you look at the main GitHub page and scroll down to "Start Menu "broken links" (10/13/2020)" it will tell you how to remove them.

We get the same if a user already has an FSLogix profile before logging onto the optimized desktop. Users with new profiles are fine.

Hope this helps.
Dave

**Comment by tmmuessig** [comment]
Thanks @davetustin
