### ISSUE TITLE
Scheduled Tasks Not Disabled

### ISSUE THREAD

**Issue by tsrob50** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#11]
The section that disables scheduled tasks is not working.  The TaskName parameter also requires the TaskPath parameter to disable tasks in subfolders.  
Disable-ScheduledTask -TaskName $Item.ScheduledTask -TaskPath $Item.TaskPath -ErrorAction SilentlyContinue

Optionally, you could use -inputobject and pass the pipeline object
Disable-ScheduledTask -InputObject $item -ErrorAction SilentlyContinue

**Comment by sandude-ms** [comment]
We will look at that soon.  Thank you for reporting that issue.

**Comment by tsrob50** [comment]
After further tests, I found the commands below worked well.
            $TaskObject = Get-ScheduledTask $Item.ScheduledTask
            Disable-ScheduledTask -InputObject $TaskObject -ErrorAction Stop | Out-Null
Thanks!

**Comment by robsmi-msfte** [comment]
Hello @tsrob50,

I just tested your changes and they seem to work great.  I am going to test those a bit more and may incorporate those into the script code.  Would that be ok with you if we did?

Thanks,

Robert M. Smith

**Comment by tsrob50** [comment]
Hello Robert,

 

Please go ahead and add as you would like.  

 

Thanks,

Travis

**Comment by robsmi-msfte** [comment]
That’s awesome.  We are happy to list you as a contributor if you like.  In any case I’ll close out the issue now.  Thank you for reporting that.

**Comment by robsmi-msfte** [comment]
Tested @tsrob50 code contribution for Scheduled Tasks, and verified it works on 2004.  I have incorporated that into a new branch and will incorporate that soon into that production code.  Thanks for reporting that.
