### ISSUE TITLE
Adding additional AppxPackages to Json file

### ISSUE THREAD

**Issue by davetustin** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#110]
Hi,

I am using the latest version of the tool and use 2009 to apply the configurations, I have been using the tool for some time now and you are doing a great job!

I went through the AppxPackages.json and disabled everything I didn't need. When I login to the desktop I see some packages are still installed, which could be added to the AppxPackages.json.

3D Viewer
Paint 3D
Mixed Reality Portal
Microsoft Store

Is this possible or are they excluded for a reason?

Thank you as always.
Dave

**Comment by tmmuessig** [comment]
Thanks for the update.  We have revisited the AppxPackages and have decided at this point to leave them as is and let the end user decide what they want to remove.  From the updated readme

AppxPackages
We have decided to update all AppxPackages.json, regardless of version of Windows, to leave all packages in the default "Installed" state. Should you wish to have them removed change "VDIState": "Enabled" to "Disabled" and they will be removed.
