### ISSUE TITLE
Failed to add HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\ReFSLog\

### ISSUE THREAD

**Issue by jamasten** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#111]
When deploying an AVD shard with 63 session hosts (21h1-evd-o365pp-g2), 2 VM's failed during VDOT configuration with the following error:

 Log Name: Virtual Desktop Optimization
Source: AutoLoggers
Date: 2/18/2022 11:09:44 PM
Event ID: 150
Task Category: (1)
Level: Error
Keywords: Classic
User: N/A
Computer: <REMOVED>
Description:
Failed to add HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\ReFSLog\

Cannot find path 'HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\ReFSLog\' because it does not exist.
Event Xml:
<Event xmlns="[http://schemas.microsoft.com/win/2004/08/events/event">](http://schemas.microsoft.com/win/2004/08/events/event%22%3E)
<System>
<Provider Name="AutoLoggers" />
<EventID Qualifiers="0">150</EventID>
<Version>0</Version>
<Level>2</Level>
<Task>1</Task>
<Opcode>0</Opcode>
<Keywords>0x80000000000000</Keywords>
<TimeCreated SystemTime="2022-02-18T23:09:44.7487676Z" />
<EventRecordID>240</EventRecordID>
<Correlation />
<Execution ProcessID="0" ThreadID="0" />
<Channel>Virtual Desktop Optimization</Channel>
<Computer><REMOVED></Computer>
<Security />
</System>
<EventData>
<Data>Failed to add HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\ReFSLog\

Cannot find path 'HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\ReFSLog\' because it does not exist.</Data>
</EventData>
</Event>

Do you know why this would fail for 2 VM's and not all 63?  We've removed the "AutoLoggers" so that we can deploy more shards without an issue but ideally, we'd like to use all the VDOT configurations.

**Comment by tmmuessig** [comment]
This is the first I have seen or heard of this.  I just kicked off a deployment in my lab so I will see how it goes and let you know.

I'm going to guess there is nothing special about these two hosts outside of the other 63, so it is even more weird.

Speaking of using ALL of the configurations, make sure you revisit the AppxPackages. We recently changed the XML file to "Enabled" meaning they are all there now by default.

**Comment by jamasten** [comment]
We've deployed 124 more session hosts with the AutoLoggers turned off and VDOT ran without any issues.  Please keep me posted if you figure out why the ReFSLog is sometimes failing.  Also, we added code to disable all AppX packages after the repo has been downloaded so no worries there ;-)

**Comment by tmmuessig** [comment]
Closing as unable to repro.  If this is still and issue, please re-open or create a new issue.
