### ISSUE TITLE
Error: Access Denied on DefaultUserSettings

### ISSUE THREAD

**Issue by ii-batman** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#114]
Hi 
getting an error when running DefaultUserSettings.

I removed all the sections after _Found HKLM:\VDOT_TEMP\Software\Microsoft\InputPersonalization\TrainedDataStore - HarvestContacts_ 

Still getting the error.

[ PACKER OUT     azure-arm: d8bbwe - DisabledByUser
 PACKER OUT     azure-arm: VERBOSE: Found
 PACKER OUT     azure-arm: HKLM:\VDOT_TEMP\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications\Microsoft.SkypeApp_kzf8qxf38zg5c
 PACKER OUT     azure-arm:  - DisabledByUser
 PACKER OUT     azure-arm: VERBOSE: Found
 PACKER OUT     azure-arm: HKLM:\VDOT_TEMP\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications\Microsoft.YourPhone_8wekyb3d8bbw
 PACKER OUT     azure-arm: e - DisabledByUser
 PACKER OUT     azure-arm: VERBOSE: Found
 PACKER OUT     azure-arm: HKLM:\VDOT_TEMP\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications\Microsoft.MicrosoftEdge_8wekyb3d
 PACKER OUT     azure-arm: 8bbwe - DisabledByUser
 PACKER OUT     azure-arm: VERBOSE: Found
 PACKER OUT     azure-arm: HKLM:\VDOT_TEMP\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications\Microsoft.549981C3F5F10_8wekyb3d
 PACKER OUT     azure-arm: 8bbwe - DisabledByUser
 PACKER OUT     azure-arm: VERBOSE: Found HKLM:\VDOT_TEMP\Software\Microsoft\InputPersonalization - RestrictImplicitInkCollection
 PACKER OUT     azure-arm: VERBOSE: Found HKLM:\VDOT_TEMP\Software\Microsoft\InputPersonalization - RestrictImplicitTextCollection
 PACKER OUT     azure-arm: VERBOSE: Found HKLM:\VDOT_TEMP\Software\Microsoft\InputPersonalization\TrainedDataStore - HarvestContacts

 **PACKER OUT     azure-arm: ERROR: Access is denied.
 PACKER OUT     azure-arm:**
 
 PACKER OUT     azure-arm: [VDI Optimize] Disable Autologgers
 PACKER OUT     azure-arm: VERBOSE: Processing Autologger Configuration File
 PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\Cellcore\
 PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\ReadyBoot\
 PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\WDIContextLog\
 PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\WiFiDriverIHVSession\
 PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\WiFiSession\
 PACKER OUT     azure-arm: VERBOSE: Updating Registry Key for: HKLM:\SYSTEM\CurrentControlSet\Control\WMI\Autologger\ReFSLog\
](url)

**Comment by tmmuessig** [comment]
Resolved by Pull Request #134
