### ISSUE TITLE
[VDI Optimize] Configuring Network Adapter Buffer Size

### ISSUE THREAD

**Issue by leeray86** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#118]
This section always breaks (Windows_VDOT.ps1 line 500) when I'm using azure image builder :
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/32316665/163912445-26d9eec6-1067-4185-a087-bf9513ffc687.png">

I noticed this today when reading some Microsoft documentation:
[Configuring Network Adapter Buffer Size](https://docs.microsoft.com/en-us/azure/virtual-machines/windows/image-builder-virtual-desktop#tips-for-building-windows-images)

"Networking - Set-NetAdapterAdvancedProperty. This is being set in the optimization script, but fails the AIB build, as it disconnects the network, this is commented out. It is under investigation."

So as the Microsoft documentation mentions, commenting it out gets around the issue. Thought I'd create an issue in case anyone runs into the issue.

If your looking through the packer customization logs the error usually presents itself like this:
`[eef188cf-85b4-4c1f-95d8-192199da9df6] PACKER OUT     azure-arm: [VDI Optimize] Configuring Network Adapter Buffer Size`
`[eef188cf-85b4-4c1f-95d8-192199da9df6] PACKER OUT ==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...`
`[eef188cf-85b4-4c1f-95d8-192199da9df6] PACKER ERR 2022/04/19 02:11:23 packer-plugin-azure plugin: 2022/04/19 02:11:23 [INFO] command 'powershell -executionpolicy bypass -file "C:/Windows/Temp/packer-elevated-shell-625e1511-f840-1e62-100c-2e7f29eb7d6a.ps1"' exited with code: 16001`
`[eef188cf-85b4-4c1f-95d8-192199da9df6] PACKER OUT ==> azure-arm: `
`[eef188cf-85b4-4c1f-95d8-192199da9df6] PACKER OUT ==> azure-arm: Deleting individual resources ...`
`[eef188cf-85b4-4c1f-95d8-192199da9df6] PACKER ERR 2022/04/19 02:11:23 packer-plugin-azure plugin: 2022/04/19 02:11:23 [INFO] RPC endpoint: Communicator ended with: 16001`

**Comment by tmmuessig** [comment]
Hi @leeray86 - a change was made last month that added a -noRestart to the end of this command that should clear this up. Please grab a new copy of the Windows_VDOT.ps1 and see if that resolves your issue.

**Comment by leeray86** [comment]
Thanks @tmmuessig, working fine now.

BTW, love your work!!

**Comment by ii-batman** [comment]
> Thanks @tmmuessig, working fine now.
> 
> BTW, love your work!!

We ALL DO! it makes our jobs so much easier! Thanks Everyone! 😉
