### ISSUE TITLE
Remove EULA

### ISSUE THREAD

**Issue by mgtvtit** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#121]
Hello, 
I would like to run this tool in my company VDI environment and use a deploy tool to run it rather than run on each individual machine. Is there a  way to remove the EULA or a command to run a silent install?

**Comment by tmmuessig** [comment]
Hi @mgtvtit  - Absolutely.  We added the "-AcceptEULA" switch you can use when calling Windows_VDOT for this very reason.
