### ISSUE TITLE
Windows Server 2016

### ISSUE THREAD

**Issue by mgtvtit** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#125]
Will this work in my organizations VDI that is running windows 2016 version 1607? 
![RVM Infor](https://user-images.githubusercontent.com/98512094/168675822-aa0c4c9c-54e0-4404-a757-d1d5e4925bd6.jpg)

**Comment by tmmuessig** [comment]
It may work, but we have never tested this on a server operating system. Use at your own discretion and test thoroughly in a test environment
