### ISSUE TITLE
Add 2 Edge (user defined) settings

### ISSUE THREAD

**Issue by robsmi-msfte** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#130]
Computer Configuration \ Administrative Templates \ Microsoft Edge \ Performance “Enable startup boost”
Computer Configuration \ Administrative Templates \ Microsoft Edge – Default Settings (users can override) “Continue running background apps after Microsoft Edge closes”

**Comment by tmmuessig** [comment]
Added and merged to Main branch
