### ISSUE TITLE
Add 2 Policy Reg entries

### ISSUE THREAD

**Issue by tmmuessig** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#132]
# Windows Components\Search “Allow Search Highlights” (Disabled)
- HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search\EnableDynamicContentInWSB

# Windows Components\News and interests “Enable news and interests on the taskbar” (Disabled)
- “News and Interests” is HKLM:\Software\Policies\Microsoft\Windows\Windows Feeds\EnabledFeeds” REG_DWORD = 0 for Disabled

**Comment by robsmi-msfte** [comment]
Added to "main".
