### ISSUE TITLE
Servers Reporting No Internet After Restart

### ISSUE THREAD

**Issue by itoc-dw** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#136]
Hi,

We have had multiple tenants using Azure Virtual Desktop (around 10) with randomly having Windows 10 multi session hosts showing "No Internet" after a restart. Servers had internet and could perform all the NCSI checks successfully. When internet is reported as down it affects office programs and now browsers etc. 

In event viewer, NCSI logs show that a SuspectDnsProbeFailed and then no further logs are recorded. As it is happening across multiple tenants, dns servers and AVD images, we deleted this optimization key and restarted all servers:

        "RegItemPath": "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkConnectivityStatusIndicator",
        "RegItemValueName": "DisablePassivePolling",
        "RegItemValueType": "DWord",
        "RegItemValue": "1",
        "VDIState": "Enabled"

Now it appears after the server is starting up if it does happen to fail on a poll it is now allowed to check again a short time later and reports internet connectivity to work. Additional NCSI logs report this unlike before. 

With Key in place:
Before, we wouldn’t get any more NCSI events after a failure (this was from the 2nd) and next event is the 3rd. 
![image](https://user-images.githubusercontent.com/62003803/178852642-32c680bd-13dc-4e8a-8dde-582619e3c7a4.png)

Now, on the same server when it failed last night.. we get same failed message 
![image](https://user-images.githubusercontent.com/62003803/178852673-b2f3fbb5-42e4-425e-839d-e723f7005cf4.png)

But looks like its recovering 15 seconds later. 
![image](https://user-images.githubusercontent.com/62003803/178852676-7f7d095b-e44a-4a45-8432-dca76e149556.png)

**Comment by robsmi-msfte** [comment]
Hello @itoc-dw,

Please make sure you are pulling down the latest version of VDOT.  Several years ago (or more) when we were still working a lot with on-premises VDI, we did some modifications to Network location.  We took that out before and now we don't touch networking components.  You should not see that with current builds of VDOT.  If you are running the latest and still see that, please let us know.

Thanks,

Robert M. Smith

**Comment by kingofi88** [comment]
This is still an issue with the latest build and caused all of our VDI's to stop reporting any internet which broke BITS and patching. 

ConfigurationFiles\PolicyRegSettings.json

        "RegItemPath": "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkConnectivityStatusIndicator",
        "RegItemValueName": "DisablePassivePolling",
        "RegItemValueType": "DWord",
        "RegItemValue": "0",
        "VDIState": "Enabled"

**Comment by robsmi-msfte** [comment]
Hello @kingofi88,
We have set "DisablePassivePolling" to "Unchanged".  The reason that is changed is because many customers we have use relatively static networks once they are up.  Since not many changes to the network, active probes usually work and the passive aren't needed.
But we hope this helps.  Let us know if not.

Thanks,

Robert M. Smith

**Comment by itoc-dw** [comment]
I don't quite understand the static network comment. We have a subnet in Azure and the AVD virtual machines start with the same IP each day, nothing really changes. No proxy etc. 

From what I can tell its that the poll check is happening before network is available on the VM and with this key it says never to check it again. Where it could be that it checks 5 seconds later and it would have worked. As mentioned it was randomly occurring across out fleet, just not sure if that VM had something a bit delayed that was required before the poll check.

**Comment by tmmuessig** [comment]
Closing this as it was resolved via #164
