### ISSUE TITLE
Scheduled Task Disable Error

### ISSUE THREAD

**Issue by benjohnsonofgem** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#137]
So the script works well for all apart from the Scheduled Task disable.

I get the below which then seems to repeat over and over:

[VDI Optimize] Disable Scheduled Tasks
Get-ScheduledTask : The system cannot find the file specified.
At C:\Optimize\Windows_VDOT.ps1:235 char:35
+ ...                   $TaskObject = Get-ScheduledTask $Item.ScheduledTask
+                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (MSFT_ScheduledTask:Root/Microsoft/...T_ScheduledTask) [Get-ScheduledTask], CimException
    + FullyQualifiedErrorId : HRESULT 0x80070002,Get-ScheduledTask

**Comment by jamasten** [comment]
I'm seeing this error too on Windows 10.

**Comment by tmmuessig** [comment]
On a fresh install of Windows 11 21H1 I am unable to repo this in my lab. Would either of you be able to share the Virtual Desktop Optimization log with us.

Also, I'm assuming that you are using the 2009 Configuration for ScheduledTasks.json file?

**Comment by jamasten** [comment]
@tmmuessig, I was letting the script determine the correct Windows version / config files. Here's the command I used:

& .\VDOT\Virtual-Desktop-Optimization-Tool-main\Windows_VDOT.ps1 -Optimizations 'All' -AdvancedOptimizations 'Edge','RemoveLegacyIE' -AcceptEULA

I've attached an export of my logs from Event Viewer but I don't think it will be much help.  It shows the first log entry for Scheduled Tasks but doesn't capture any of the errors in that configuration.
[vdot.evtx.zip](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/files/9584963/vdot.evtx.zip)

**Comment by tmmuessig** [comment]
@jamasten - Thanks.. I have not see this error before that I am seeing in your logs with regards to Scheduled Tasks.. "Attempt to use a file handle to an open disk partition for an operation other than raw disk I/O. "

I'm going to have to investigate some more on this one.

**Comment by jamasten** [comment]
Here are the OS specifics:
<img width="494" alt="Screen Shot 2022-09-16 at 10 42 57 AM" src="https://user-images.githubusercontent.com/61800683/190666060-5bb957a1-2a80-46a5-bb76-8e6e813ed5f1.png">

**Comment by robsmi-msfte** [comment]
I just tested on a Win10 Enterprise, 21H2 VM, only the Scheduled Tasks.  This is the result:

```PS C:\Optimize> .\Windows_VDOT.ps1 -Optimizations ScheduledTasks -AcceptEULA -Verbose
[VDI Optimize] Disable Scheduled Tasks
VERBOSE: Attempting to disable Scheduled Task: AnalyzeSystem
VERBOSE: Attempting to disable Scheduled Task: Cellular
VERBOSE: Attempting to disable Scheduled Task: Consolidator
VERBOSE: Attempting to disable Scheduled Task: Diagnostics
VERBOSE: Attempting to disable Scheduled Task: FamilySafetyMonitor
VERBOSE: Attempting to disable Scheduled Task: FamilySafetyRefreshTask
VERBOSE: Attempting to disable Scheduled Task: MapsToastTask
VERBOSE: Attempting to disable Scheduled Task: Microsoft Compatibility Appraiser
VERBOSE: Attempting to disable Scheduled Task: Microsoft-Windows-DiskDiagnosticDataCollector
VERBOSE: Attempting to disable Scheduled Task: NotificationTask
VERBOSE: Attempting to disable Scheduled Task: ProcessMemoryDiagnosticEvents
VERBOSE: Attempting to disable Scheduled Task: Proxy
VERBOSE: Attempting to disable Scheduled Task: QueueReporting
VERBOSE: Attempting to disable Scheduled Task: RecommendedTroubleshootingScanner
VERBOSE: Attempting to disable Scheduled Task: RegIdleBackup
VERBOSE: Attempting to disable Scheduled Task: RunFullMemoryDiagnostic
VERBOSE: Attempting to disable Scheduled Task: ScheduledDefrag
VERBOSE: Attempting to disable Scheduled Task: SpeechModelDownloadTask
VERBOSE: Attempting to disable Scheduled Task: Sqm-Tasks
VERBOSE: Attempting to disable Scheduled Task: SR
VERBOSE: Attempting to disable Scheduled Task: StartComponentCleanup
VERBOSE: Attempting to disable Scheduled Task: WindowsActionDialog
VERBOSE: Attempting to disable Scheduled Task: WinSAT
VERBOSE: Attempting to disable Scheduled Task: XblGameSaveTask
VERBOSE: Attempting to disable Scheduled Task: UsbCeip
VERBOSE: Attempting to disable Scheduled Task: VerifyWinRE
VERBOSE: Attempting to disable Scheduled Task: Work Folders Logon Synchronization
VERBOSE: Attempting to disable Scheduled Task: Work Folders Maintenance Work


Thank you from the Virtual Desktop Optimization Team
WARNING: A reboot is required for all changes to take effect

PS C:\Optimize>
```

**Comment by robsmi-msfte** [comment]
Could someone currently having the Scheduled Tasks problem attach three items in a zip file:

- Copy of your "Windows_VDOT.ps1"
- Copy of your 2009\ConfigurationFiles\'ScheduledTasks.json'
- Output of this command line command:
`Schtasks > Schtasks.txt`

**Comment by tmmuessig** [comment]
@benjohnsonofgem - could you share how you are running Windows_10. command you are running with the parameters?

**Comment by jamasten** [comment]
@robsmi-msfte here are the requested artifacts:
[Windows_VDOT.ps1.zip](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/files/9586986/Windows_VDOT.ps1.zip)
[ScheduledTasks.json.zip](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/files/9586990/ScheduledTasks.json.zip)
[Schtasks.txt](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/files/9586992/Schtasks.txt)

**Comment by robsmi-msfte** [comment]
> 

I ran a bunch of tests and was almost able to replicate the problem "The system cannot find the file specified".  The difference between the error listed above is the line number reference:

@benjohnsonofgem At C:\Optimize\Windows_VDOT.ps1:**235 char:35**
@robsmi-msfte At C:\Optimize\Windows_VDOT.ps1:**274 char:35**

It makes me wonder if you have an older version of VDOT.  We updated quite a bit recently.  I would try downloading a new copy, customize it, test that and let us know the results.

Thanks,

Robert Smith

**Comment by jamasten** [comment]
@robsmi-msfte, every time I run VDOT i'm pulling the latest ZIP from GitHub.  So versioning wouldn't be my issue.

**Comment by jamasten** [comment]
```powershell
    if($ImagePublisher -eq 'MicrosoftWindowsDesktop' -and $ImageOffer -ne 'windows-7')
    {
        # Download VDOT
        $URL = 'https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/archive/refs/heads/main.zip'
        $ZIP = 'VDOT.zip'
        Invoke-WebRequest -Uri $URL -OutFile $ZIP
        
        # Extract VDOT from ZIP archive
        Expand-Archive -LiteralPath $ZIP -Force
        
        # Fix to disable AppX Packages
        # As of 2/8/22, all AppX Packages are enabled by default
        $Files = (Get-ChildItem -Path .\VDOT\Virtual-Desktop-Optimization-Tool-main -File -Recurse -Filter "AppxPackages.json").FullName
        foreach($File in $Files)
        {
            $Content = Get-Content -Path $File
            $Settings = $Content | ConvertFrom-Json
            $NewSettings = @()
            foreach($Setting in $Settings)
            {
                $NewSettings += [pscustomobject][ordered]@{
                    AppxPackage = $Setting.AppxPackage
                    VDIState = 'Disabled'
                    URL = $Setting.URL
                    Description = $Setting.Description
                }
            }

            $JSON = $NewSettings | ConvertTo-Json
            $JSON | Out-File -FilePath $File -Force
        }

        # Run VDOT
        & .\VDOT\Virtual-Desktop-Optimization-Tool-main\Windows_VDOT.ps1 -Optimizations 'All' -AdvancedOptimizations 'Edge','RemoveLegacyIE' -AcceptEULA


        Write-Log -Message 'Optimized the operating system using VDOT' -Type 'INFO'
    }   
```

**Comment by benjohnsonofgem** [comment]
Hey guys, glad this has been picked up. I should be able to re-test later this afternoon or if not first thing tomorrow morning. I will upload logs when I can.

**Comment by mdosullivan1981** [comment]
I am seeing this with Windows 11 but it appears it maybe an issue with running Get-ScheduledTask or Disable-ScheduledTask or other commandlets for ScheduledTasks runing as the local admin.  If we run PowerShell using an non-administrator Powershell, it works.

**Comment by robsmi-msfte** [comment]
That is interesting because from the beginning of the VDOT tool, elevation has been required for certain tasks to run.  We will take a look from that angle and see if we can find anything.

**Comment by benjohnsonofgem** [comment]
Quick update. My original issues with this have disappeared with latest version download.

**Comment by tmmuessig** [comment]
Outstanding. I'm going to close this, but if it appears again, please open a new issue and we will dig into it.
