### ISSUE TITLE
Feature Request: Add a Watermark/Timestamp of version of VDOT Deployed

### ISSUE THREAD

**Issue by brmcmill** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#138]
Hey Team!  Not an issue -- but a recommendation/request: Would it help if there was a Watermark or Timestamp of the version of VDOT deployed?  That's if there isn't already something available :).

That may help with customers determining the _last_ version that was deployed and _if_ they need to download the latest version available.  I'm sure this could be handled a number of ways (Reg key, Log, etc).  Happy to help test any scenarios as well.  Hope this helps!

**Comment by tmmuessig** [comment]
This is a great idea and one we have been kicking around for a while. 

What would work best in your opinion, something written to the registry in our own VDOT key or in the existing logs we already have at runtime?

**Comment by jamasten** [comment]
+1 for registry

**Comment by brmcmill** [comment]
Hey @tmmuessig -- I like the registry idea.  Probably lessens the likelihood of a log being cleared out as I've observed a lot of times, the registry may be locked down for users which could make that more secure for admins.  Hope that helps!

**Comment by tmmuessig** [comment]
@brmcmill  and @jamasten  - How would this work for you?  Need more information, or is this what you are looking for?  

![image](https://user-images.githubusercontent.com/7741612/181784556-39352ad1-fca5-4280-bdb8-3f5d690dc7a8.png)

Explanation of Version:
2.0.2009.1 - This will signify the following:
2 - Major changes to the .ps1 file
0 - Minor changes to the .ps1 file
2009 - What version of Windows 10 the latest configuration files support
0 - Minor changes to the Windows configuration changes

**Comment by brmcmill** [comment]
@tmmuessig  that is perfect!

**Comment by jamasten** [comment]
@tmmuessig looks great to me!  Thanks!

**Comment by tmmuessig** [comment]
@brmcmill and @jamasten  Added this in the branch https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/tree/versionbranding 

Give it a try and let me know if you have any issues.  I'll push it to main early next week if all is good.

**Comment by tmmuessig** [comment]
@jamasten  and @brmcmill  - This request has been added to the latest release.

**Comment by brmcmill** [comment]
Thanks again @tmmuessig  -- sorry I didn't get back to you on testing.  Thanks for the support!

**Comment by tmmuessig** [comment]
All good, but be advised, we have changed the script a little.  Make sure to read the updated Readme.md.

Basically, you have to pass in a parameter now instead of the default of passing in nothing and getting everything.
