### ISSUE TITLE
Task Host Window Synchronize Language Settings

### ISSUE THREAD

**Issue by mkaey** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#14]
The Tool works really great in general, but I realized a minor drawback after preparing my image using the script. When users log off or reboot the machine sometimes there will be a message from the task host window telling you that the Language Synchronization is still running. I attached a screenhot of the german version 

![image](https://user-images.githubusercontent.com/50746943/96121299-2de73880-0ef0-11eb-851d-65eb448a4ead.png)

**Comment by tmmuessig** [comment]
Unable to replicated.  If this is still happening please reopen this issue

**Comment by hristo1985** [comment]
i have the exact same issue. When sign out from horizon client i get this massage
