### ISSUE TITLE
EdgeSettings.json registry value incorrect 

### ISSUE THREAD

**Issue by Jongzz** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#140]
Hi Team,

Love the tool, thanks for all your efforts!

One issue we found recently, the registry value in the EdgeSettings.json for the IE restricted launch setting should be "disable" - NotifyDisableIEOptions not "disabled" - NotifyDisabledIEOptions

Ref

        "Description": "This policy lets you restrict launching of Internet Explorer as a standalone browser",
        "RegItemPath": "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Internet Explorer\\Main",
        "RegItemValueName": "**NotifyDisabledIEOptions**

Thanks,
Jon

**Comment by tmmuessig** [comment]
Thanks for the catch @Jongzz This has been resolved
