### ISSUE TITLE
Win10 Ent 2004 Outlook / Domain Join GUI

### ISSUE THREAD

**Issue by journeym** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#15]
Seems that after applying some of the listed gpo optimizations on my 2004 VDI machines wont work the following fuctionality:

Domain Join using GUI (Control Panel > System > etc)
Outlook autodiscover using GUI, for example, first time connecting to exchange, and further on. (Though autodiscover test works fine, all green).
Problems were gone after i deleted registry.pol in system32\GroupPolicy\Machine
I have exported it using lgpo before deleting, maybe someone more experienced can point me out to exact values that can cause this.
Lgpo export https://pastebin.com/zXa19Puc

**Comment by sandude-ms** [comment]
Hello @journeym,

You might try with the latest settings, by downloading the entire repo, then running this:

.\Win10_VirtualDesktop_Optimize.ps1 -WindowsVersion 2009 -Verbose

See if that makes any difference.

Thanks,

Robert Smith
