### ISSUE TITLE
Photos Needs to be Reinitialized.  Default for Photo Viewer is "Microsoft WinRT Storage API" on AVD Session Hosts

### ISSUE THREAD

**Issue by brmcmill** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#154]
I've noticed when we try to enforce Default App Associations via GPO, it still will not force **Photos** as the default **Photo viewer** application.  What each user has to do is manually open up the Photos app within their profile session, and then they can set Photos as the default Photo viewer.  

In my customer's environment, we do not disable the Microsoft Photos Appx Package for Windows 10 Multi-Session Images for Azure Virtual Desktop (AVD).  I'll have to check if this is also affecting Windows 11.  I'm not sure if this is a Windows bug or something related to VDOT when the AppxPackage removal feature is run.

![image](https://user-images.githubusercontent.com/26752719/209442821-e9eb0999-7678-478e-aa37-7821a201ee67.png)

**Comment by robsmi-msfte** [comment]
Hello @brmcmill,

Have you tested on a device that has not had the VDOT tool run on it?  If the issue still occurs there, then you might want to open a case with Microsoft CSS.  But if the issue ONLY occurs when the VDOT tool has been run, then that's something we can look into.

Thanks,

Robert Smith

**Comment by brmcmill** [comment]
Hey @robsmi-msfte  -- will do, thank you for the recommendation.  Plan to test it this week.

**Comment by robsmi-msfte** [comment]
One other thing @brmcmill...check the other imagine apps, such as Paint and Paint 3D.  Perhaps removing one of those has caused this issue.

**Comment by brmcmill** [comment]
Hey @robsmi-msfte -- this is from a standard Marketplace Image within AVD - Windows 10 21H2 - without VDOT.  We need to test our code too with and without VDOT to be limit what it is, but for sure it's not anything to with the Marketplace Image + FSLogix.

![image](https://user-images.githubusercontent.com/26752719/214199748-e76702fe-2355-46ef-9eff-56116d652b58.png)

**Comment by brmcmill** [comment]
This was on a Windows 10 21H2 System deploying **VDOT with our deployment code**.  We'll test it tomorrow **without adding VDOT**.

![image](https://user-images.githubusercontent.com/26752719/214460716-4dad1a5b-4e26-4510-8807-6576f18fe8df.png)

**Comment by brmcmill** [comment]
> One other thing @brmcmill...check the other imagine apps, such as Paint and Paint 3D. Perhaps removing one of those has caused this issue.

Paint and Paint3D are not being removed.  Just to note.

**Comment by brmcmill** [comment]
Hey @robsmi-msfte  -- here's a deployment with **running our code, but WITHOUT VDOT**.  So I believe it's something within VDOT that is causing the Storage API assignment for Photo Viewer, Video Player, and other default apps.

![image](https://user-images.githubusercontent.com/26752719/214465589-ba7595b4-96a0-4980-924d-b8073fdc70af.png)

**Comment by brmcmill** [comment]
The switches are we are using, to note, are below:

```PowerShell
Windows_VDOT.ps1 -Optimizations 'All' -AdvancedOptimizations 'Edge' -AcceptEULA
```

**Comment by brmcmill** [comment]
Here's the AppxPackage.json file we are using.

[AppxPackages.json.txt](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/files/10495625/AppxPackages.json.txt)

**Comment by robsmi-msfte** [comment]
Brandon...if you have a chance, try this.  Go the folder where you have VDOT.  Find the '2009' folder and go there.  Find the sub-folder called 'ConfigurationFiles'.  Find and delete (or rename) the file "DefaultAssocationsConfiguration.xml".  Now run VDOT exactly as you have before and report the result.  I didn't see any problem with the Appx...txt file you sent earlier.

Thanks,

Robert M. Smith

**Comment by brmcmill** [comment]
Thanks @robsmi-msfte  -- will do!

**Comment by brmcmill** [comment]
I can test modifying that part of the script just to see if it will run.

**Comment by chibs89** [comment]
Why don't you just change the regkey to "not enabled"? You don't have to change the script itself. 
"Description": "This policy specifies the path to a file (e.g. either stored locally or on a network location) that contains file type and protocol default application associations.",
        "RegItemPath": "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\System",
        "RegItemValueName": "DefaultAssociationsConfiguration",
        "RegItemValueType": "String",
        "RegItemValue": "c:\\windows\\system32\\defaultassociations.xml",
        "VDIState": "Enabled"
    },

**Comment by brmcmill** [comment]
Same issue.  I tried both the forked repo and disabling it in the json above.
![image](https://user-images.githubusercontent.com/26752719/215175535-fc3687bd-e8b8-4c5d-960c-4786c4c423e1.png)

**Comment by brmcmill** [comment]
I even tried to comment this out, same result

image



image

**Comment by brmcmill** [comment]
I retract my statement.  I had to remove my preexisting profile.  I used the fork you provided @robsmi-msfte and it worked like a champ!  Thank you so much for your patience and support!

![image](https://user-images.githubusercontent.com/26752719/215215765-ee7b95f2-fce1-49fe-9610-c07d1118370e.png)

**Comment by robsmi-msfte** [comment]
We removed code that was changing some of the Edge default settings.  Though seemingly unrelated, these are no longer needed now that Chromium Edge is prevalent and IE 11 is no more.
