### ISSUE TITLE
Add exclusion for removing 'packer*.ps1' in temp folder to line 743 in Windows_VDOT.ps1

### ISSUE THREAD

**Issue by KorZijl** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#155]
In Windows_VDOT.ps1 you've excluded the removal of temporary packer files from the '$env:windir\Temp' folder in line 731, but that exclusion is missing in line 743 for the '$env:TEMP' folder.
Both those paths with environment variables are pointing to 'C:\Windows\Temp' in my case.

Question: Can you add that exclusion also to line 743 cause that line is still removing my temporary packer files from the temp folder.

**Comment by jamasten** [comment]
This problem is also impacting the Custom Image Build solution in the AVD Accelerator.

**Comment by tmmuessig** [comment]
I just updated this, please pull the latest version.  Once you verify, we can close this, but I'll leave it open until then.

**Comment by tmmuessig** [comment]
Closing as the fix is now confirmed
