### ISSUE TITLE
README.md - Incorrect VDIState parameter explanation

### ISSUE THREAD

**Issue by ddmitrovic** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#159]
The paragraph within README.md which states "The JSON parameter that this tool uses to determine whether or not to apply a setting is 'VDIState'. If the 'VDIState' parameter in the respective .JSON file is set to Disabled, the optimization setting will be applied. If 'VDIState' is set to anything else, the setting will not be applied." is not entirely correct."

If the registry settings within PolicyRegSettings.json need to be applied the 'VDIState' must be set to "Enabled", otherwise they will get ignored.

**Comment by tmmuessig** [comment]
We are in discussions on making these more obvious as to if the setting is 'set' vs 'not set'.  Once that decision is made, we will update the verbiage in the documentation.  But thanks for pointing this out.
