### ISSUE TITLE
Use on Windows Server 2019 RDS

### ISSUE THREAD

**Issue by glshnu** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#160]
HI, can i use the Tool on Windows Server 2019/2016/2022 RDS?

**Comment by tmmuessig** [comment]
Technically, yes you can use it on Windows Server. However, it has never been tested for Windows Server, nor do we support this configuration. 

I have run it on a Server OS and has no issues, but again that was just sort of "seeing what happened", and this server was not in production, and I didn't monitor it for any issues afterwards.  I merely was just seeing if it would run and complete on the platform.
