### ISSUE TITLE
Do not disable VSS Service by default

### ISSUE THREAD

**Issue by eponerine** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#162]
Can we please change the default behavior of `-optimize services` to not have the VSS service disabled by default? This will kill Production Checkpoints on Hyper-V (and potentially app-aware backups from backup software).

Yes, people should not be blindly running this script without understanding what it does, but killing VSS doesn't seem to be the correct default behavior (unless someone else disagrees).

**Comment by robsmi-msfte** [comment]
Hello @eponerine,

Done.  Thanks for the feedback.

Thanks,

Robert Smith
