### ISSUE TITLE
Disabling UTCService (DiagTrack) will interfere with Defender.

### ISSUE THREAD

**Issue by Anakha56** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#163]
So I am testing this out on a test AVD. Ran the Optimizations Services, rebooted and then ran the Client Analyzer for Defender and it highlighted the following:

"UTC Service is Disabled. This device may not be able to upload cyber data."

https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/troubleshoot-onboarding?view=o365-worldwide#ensure-the-diagnostic-data-service-is-enabled

According to the the tools documentation:

Connected User Experiences and Telemetry service, manages the event driven collection and transmission of diagnostic and usage information (used to improve the experience and quality of the Windows Platform) when the diagnostics and usage privacy option settings are enabled under Feedback and Diagnostics.

It may be better to leave this service as Unchanged for the future? Or at least highlight in the Services.json that this service and possibly other diagnostic services are needed for Defender.

**Comment by robsmi-msfte** [comment]
Hello @Anakha56.  We changed DiagTrack to "unchanged" a while ago.  I think we're going to just remove that block from the .JSON file.  Some of the settings in there were more pertinent to on-premises VDI which in many cases did not have any access to the Internet.  The tool evolved for AVD and continues on.

**Comment by Anakha56** [comment]
Huh, I could have sworn I downloaded an updated version of the tool. My sincere apologies, don't know how I missed that :).

**Comment by robsmi-msfte** [comment]
No problem at all.  We had an issue with that before so we're going to just remove that block from the config file.
