### ISSUE TITLE
Windows 11: Disable/Skip First Logon Microsoft Account Creation Screen?

### ISSUE THREAD

**Issue by KptnKMan** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#169]
Hi Team,
We use VDOT in our organisation, and are in the process of rolling out Windows 11 desktops.
There is an issue whereby when new Windows 11 systems are built, at first startup, the OS presents a screen to create a Microsoft Account. This happens regardless of domain join or other configuration.

Once an account is entered, the session closes, and every subsequent startup/logon this never appears again.

The screen looks like this:
![image](https://user-images.githubusercontent.com/12234043/230346695-d25ba2be-0ad5-4c45-ad03-6a8e64c559dd.png)

There is a sysprep setting to disable this, found in the Windows System Image Manager tool, which looks like the following, present in `Pass 7 oobeSystem`:

`Microsoft-Windows-Shell-Setup –> OOBE -> HideOnlineAccountScreens = True`

![image](https://user-images.githubusercontent.com/12234043/230348239-92346d74-a128-487c-8524-249162207acb.png)

I have been searching through the VDOT tool, and I cannot determine if this is is within its capability.
Does the VDOT have facility to manage this?

Also, is there another way, other than creating a custom unattend.xml for sysprep?

**Comment by tmmuessig** [comment]
VDOT is not designed to accomplish this ask.
