### ISSUE TITLE
Apply security baseline recommendations

### ISSUE THREAD

**Issue by dhirschfeld** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#17]
I'm not sure if this is already being done? If not it would be great to also include the baelie security recommendations.

***xref:*** https://techcommunity.microsoft.com/t5/microsoft-security-baselines/security-baseline-draft-windows-10-and-windows-server-version/ba-p/1799721

**Comment by tmmuessig** [comment]
Understand where you are coming from, but at this time we are focusing more on the optimization than additional security implementations, which we expect that admins are implementing according to their company standards.
