### ISSUE TITLE
Windows 11: Issue with Snipping Tool / DefaultApps

### ISSUE THREAD

**Issue by brmcmill** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#176]
Hey Team, we started noticing after running VDOT, the Snipping Tool app in Windows 11 defaults to "Microsoft WinRT Storage API".  We ensured the default app associations for Edge are set to "Unchanged". Right now, we have to help walk through users on resetting the defaultapp for the Snipping Tool within their user profile/session within AVD.  Here are example screenshots providing the workaround.  We'd like to see if there's something we can do to fix this after running VDOT.

**What users see**
![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/26752719/15be6aa7-b800-4e9c-8d34-842c776489fc)

![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/26752719/6179c401-42b7-4f25-9e03-8d8d9cecb4be)

**When Corrected**
![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/26752719/d1ea9a5f-bf04-4e6a-bc67-3258f4df5b7d)

**Comment by jasveith** [comment]
Brandon - I'm a bit confused... what are we suppose to do to correct the app association for Snipping Tool?  

"We ensure the default app associations for Edge are set to "Unchanged". Example screenshots below" ???

**Comment by brmcmill** [comment]
No problem, so before we had this problem with Windows 10 and _Photos_.  This was a previous issue we submitted awhile back, and the fix was to set in the **EdgeSettings.json** file to _DefaultAppAssociations_ to **Unchanged**.  Now that my customer is on Windows 11, we started noticing when they would try to use the Snipping Tool, we had to redirect them to manually set the defaultapp in their profile/session within on AVD.  We tried to enforce an AppAssociations.xml file to enforce ms-screensketch to the Snipping Tool, but it will not stick for some reason.  So we're just trying to figure out why that is happening and if it's a result of running VDOT or something else.

This was the older issue I had opened:
https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/issues/154

**Comment by tmmuessig** [comment]
@brmcmill  - What happens if you comment out line 644, the line that says `Copy-Item .\ConfigurationFiles\DefaultAssociationsConfiguration.xml $key.RegItemValue -Force` ?

Even though it is set to unchanged by default, it should not be getting applied like you said.  I'm wondering if it is for some reason, even though the code says it should not be getting set.

**Comment by brmcmill** [comment]
Thanks @tmmuessig -- I will test that out!

**Comment by brmcmill** [comment]
Hey @tmmuessig -- so far that appears to have worked.  I'll do some more testing to make sure.

**Comment by brmcmill** [comment]
Closing/Cancelling.
