### ISSUE TITLE
New tag release

### ISSUE THREAD

**Issue by raptorrico** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#178]
Hello,

I notice that the latest tag release is September 2022. Within code I am downloading VDOT from the tag set as latest but there has been significant changes within the main branch in 12 months.

Please could I ask, when do you expect to update the latest tag?

Thanks

**Comment by tmmuessig** [comment]
We have a few config changes coming soon and will be updating to a new release/tag.

**Comment by raptorrico** [comment]
Hello, do you have an ETA on a new release/tag? I'd hoped releases would be more regular, with the last being Sep 22.

**Comment by tmmuessig** [comment]
@raptorrico - Ironically I was thinking about this over the holidays.  @sandude-ms and I will be discussing this as well as updates for VDOT in the next week or so.

**Comment by robsmi-msfte** [comment]
I just created a new release.
