### ISSUE TITLE
*Suggestion* Disable Scheduled Task CloudRestore

### ISSUE THREAD

**Issue by Anakha56** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#179]
The new Windows Back up creates a scheduled task called CloudRestore. Not needed in an AVD environment and is disabled for Enterprise environments anyway so why leave a task enabled ready to fire :).

Task Scheduler --> Microsoft --> Windows --> CloudRestore

**Comment by robsmi-msfte** [comment]
Hello @Anakha56,

I am submitting a PR to add the 'Restore' task. I agree it's most likely never needed for AVD and would never apply to domain-joined. I am leaving the entry to 'unchanged'.  To disable that task, just edit the .JSON file and change that 'VDIState' to 'disabled'.

Thanks,

Robert Smith
