### ISSUE TITLE
20H2 support ?

### ISSUE THREAD

**Issue by maleroyfr** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#18]
Hello !

Can I use the script on a 20H2 VM ? (Azure Marketplace - Windows 10 20H2 Multisession)
Any testing/feedback yet ?

Thank you !

**Comment by tmmuessig** [comment]
There should be no issues running this against a 20H2 multisession. We have not fully evaluated it yet but I don’t expect there to be any issues.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by maleroyfr** [comment]
thanks for the quick answer!

**Comment by maleroyfr** [comment]
Just tested, looks good overall but strangely Video Editor is still there. I was under the impression that it should have been remove with "Photo" but ... stil there :(

**Comment by tmmuessig** [comment]
On my system, when I remove Photos, the Video editor is removed as well.  Let me do some additional testing and see what I can come up with.

**Comment by msft-jasonparker** [comment]
@maleroyfr, Please check out the latest version.  We've included support for 20H2 along with allowing the script to only execute specific tasks by using switch parameters.
