### ISSUE TITLE
OneDrive isn't uninstalled on Windows 11

### ISSUE THREAD

**Issue by achawla5** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#180]
On the following Win11 images, OneDrive doesn't get uninstalled:

- Windows 11 Enterprise multi-session
- Windows 11 Enterprise multi-session + Microsoft 365 Apps
- Windows 11 Enterprise multi-session + Microsoft 365 Apps, 22H2

**Comment by robsmi-msfte** [comment]
Hello @achawla5,

When you ran the VDOT tool, did you specify the '-AdvancedOptimizations' setting and then specify either 'All' or 'RemoveOneDrive'?

I tested the current version of VDOT on Windows 11 EVD.  After running VDOT I don't have any outward trace of OneDrive installed.  When you search for 'C:\OneDrive*.* /s' you get a few .ICO files and a few folders.  I am putting in a PR now to remove the folders.  This will leave two .ICO files.  Those files cannot be deleted easily, so I am going to stop there.

You might check the VDOT event log ('Applications and Services Logs\Virtual Desktop Optimization') and look for the event where VDOT start, like this:

![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/61853161/710c98f9-99dd-4f09-9a16-c4a032407acd)

Then look for the OneDrive events:

![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/61853161/472459fc-85fe-4f5e-9665-7b0b137bd1bb)
![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/61853161/4567600d-58ac-41d3-b462-2cd5e87c0c12)
![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/61853161/f9cf4ba5-5883-4f6f-b5ee-7d144c9a582f)

See if this help.  I will submit the PR now.

Thanks,

Robert Smith

**Comment by tmmuessig** [comment]
@achawla5 l just merged a code fix that Robert pushed that should fix your issue. Let us know if you still are having issues

**Comment by robsmi-msfte** [comment]
No comment for some time.  Closing.
