### ISSUE TITLE
Windows 11 22H2: GetStarted AppxPackage does not remove

### ISSUE THREAD

**Issue by brmcmill** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#183]
Hey Team -- this might be a bug with Windows 11 22H2 as I thought this worked well with earlier versions and Windows 10.  It does not seem like you can remove `GetStarted` appxpackage anymore.

**Comment by ii-batman** [comment]
Same here, this is my apppackages.json:
` {
    "AppxPackage": "Microsoft.Getstarted",
    "VDIState": "Disabled",
    "URL": "https://www.microsoft.com/en-us/p/microsoft-tips/9wzdncrdtbjj",
    "Description": "Windows 10 tips app"
  },
  {`

**Comment by robsmi-msfte** [comment]
Hello @brmcmill and @ii-batman ,

I tested on Windows 10 22H2 Enterprise with a default installation, and these are the results:

- 'GetStarted' Provisioned to current user, staged to 'SYSTEM'
- I try to remove 'GetStarted' with Remove-AppxPackage -AllUsers and get an error
- I try to remove 'GetStarted with Remove-AppxPackage on just my profile and it works
- I try to remove 'GetStarted with Remove-AppxPackage from 'SYSTEM' and that works.
- I check and there is still a provisioned package called 'Microsoft.GetStarted'.
I apply initial checkpoint from day of install and log back in.
- I remove the payload with 'Remove-AppxProvisionedPackage' and 'GetStarted' is still provisioned to my current profile.
- I can remove 'GetStarted' from my profile with 'Remove-AppxPackage'.

This is why VDOT works well in places like Azure Image Builder or Packer.  Packer for example has an ephemeral profile that is deleted and cleaned up in the registry before SYSPREP when building an image using Packer.  Therefore, we don't care about apps provisioned to that account.
There are still apps provisioned to the "account" 'SYSTEM'.  Though when we sweep through and remove payloads, most of those that are in the state 'Staged' are no longer staged to 'SYSTEM'.  What I do in code is then remove the few that are left 'Staged' to 'SYSTEM'.  In this case I am removing any Store app or package that cannot be updated without connecting to the Store.

I have code and payloads of the updated Store app packages.  I install those as part of the image build.  This takes care of getting Store app packages at least updated to that point in time.

Windows 11: 23H2:
Initial installation, not connected to Internet:

```
PS C:\Windows\system32> Get-AppxPackage -AllUsers -Name 'Microsoft.GetStarted'

Name                   : Microsoft.Getstarted
Publisher              : CN=Microsoft Corporation, O=Microsoft Corporation, L=Redmond, S=Washington, C=US
Architecture           : X64
ResourceId             : 
Version                : 10.2204.1.0
PackageFullName        : Microsoft.Getstarted_10.2204.1.0_x64__8wekyb3d8bbwe
InstallLocation        : C:\Program Files\WindowsApps\Microsoft.Getstarted_10.2204.1.0_x64__8wekyb3d8bbwe
IsFramework            : False
PackageFamilyName      : Microsoft.Getstarted_8wekyb3d8bbwe
PublisherId            : 8wekyb3d8bbwe
PackageUserInformation : {S-1-5-21-... [Robert]: Installed}
IsResourcePackage      : False
IsBundle               : False
IsDevelopmentMode      : False
NonRemovable           : False
Dependencies           : {Microsoft.VCLibs.140.00_14.0.30704.0_x64__8wekyb3d8bbwe, Microsoft.UI.Xaml.2.7_7.2203.17001.0_x64__8wekyb3d8bbwe, 
                         Microsoft.NET.Native.Framework.2.2_2.2.29512.0_x64__8wekyb3d8bbwe, Microsoft.NET.Native.Runtime.2.2_2.2.28604.0_x64__8wekyb3d8bbwe}
IsPartiallyStaged      : False
SignatureKind          : Store
Status                 : Ok
```

```
PS C:\Windows\system32> Get-AppxProvisionedPackage -Online | Where DisplayName -EQ 'Microsoft.GetStarted'

DisplayName  : Microsoft.Getstarted
Version      : 2021.2204.1.0
Architecture : neutral
ResourceId   : ~
PackageName  : Microsoft.Getstarted_2021.2204.1.0_neutral_~_8wekyb3d8bbwe
Regions      : all

PS C:\Windows\system32> Get-AppxPackage -AllUsers -Name 'Microsoft.GetStarted' | Remove-AppxPackage -AllUsers

PS C:\Windows\system32> Get-AppxPackage -AllUsers -Name 'Microsoft.GetStarted'

PS C:\Windows\system32> 

PS C:\Windows\system32> Get-AppxProvisionedPackage -Online | Where DisplayName -EQ 'Microsoft.GetStarted'

PS C:\Windows\system32> 
```

Interesting that the 'GetStarted' app payload was removed when the only provisioned user had it installed.  I believe that's the behavior when you run 'Remove-AppxPackage -AllUsers'.

In any event, I hope this helps explain the behavior, and displays that you can still remove 'GetStarted'.
