### ISSUE TITLE
HKLM:\\SOFTWARE\\SOFTWARE Is it correct?

### ISSUE THREAD

**Issue by ursacom** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#184]
{
        "RegItemPath": "HKLM:\\SOFTWARE\\SOFTWARE\\Policies\\Microsoft\\Windows\\System",
        "RegItemValueName": "DisableAcrylicBackgroundOnLogon",
        "RegItemValueType": "DWord",
        "RegItemValue": "1",
        "VDIState": "Enabled"
    },
    {
        "RegItemPath": "HKLM:\\SOFTWARE\\SOFTWARE\\Policies\\Microsoft\\Windows\\System",
        "RegItemValueName": "DisableLockScreenAppNotifications",
        "RegItemValueType": "DWord",
        "RegItemValue": "1",
        "VDIState": "Enabled"
    },
In https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/main/2009/ConfigurationFiles/PolicyRegSettings.json

**Comment by robsmi-msfte** [comment]
#192 will fix this one.  Thank you for reporting.
