### ISSUE TITLE
EventSource AdvancedOptimizations missing if older VDOT was previously run

### ISSUE THREAD

**Issue by brentil** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#185]
If you've ever previously run VDOT on a system it built the Virtual Desktop Optimization Event Log category.  At the time AdvancedOptimizations didn't exist so were not added to the list of Event Sources of it.  Currently the code on line 126 only detects if the Virtual Desktop Optimization Event Log category exists and then continues on if it does which means the AdvancedOptimizations never gets added.  Then if you use the AdvancedOptimizations section when it tries to log it throws tons of errors as it doesn't exist as a source to use.

![image](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/assets/309174/2ceffb22-b542-4422-9962-84da4e62570c)

Maybe a command to rebuild the Virtual Desktop Optimization Event Log category or check for the or just re-write the sources every time?  Looking at the MS docs for New-EventLog you can call it again with new sources to just add them.  I tested running the code below from lines 129-130 again and it complains about the ones that exist already but then just only adds the one new item.

```
$EventSources = @('VDOT', 'WindowsMediaPlayer', 'AppxPackages', 'ScheduledTasks', 'DefaultUserSettings', 'Autologgers', 'Services', 'NetworkOptimizations', 'LGPO', 'AdvancedOptimizations', 'DiskCleanup')
New-EventLog -Source $EventSources -LogName 'Virtual Desktop Optimization'
```

**Comment by tmmuessig** [comment]
@brentil - Great catch as I've not run into this in my testing.  I'll take it for action and update it as quickly as possible.

**Comment by brentil** [comment]
> @brentil - I just added commit [673b8bf](https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/commit/673b8bff434a2f33a8fa06133137d7e651d34a50) and it's working on my end to address this issue. Can you give it a test. If it resolves your error, I'll merge it to main.

@tmmuessig - Just tested that fix and it worked perfectly on a system I knew would have thrown the error!

**Comment by tmmuessig** [comment]
Closing as the issue has been fixed and merged to Main
