### ISSUE TITLE
New Windows Store apps to remove

### ISSUE THREAD

**Issue by brentil** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#188]
MS has made it so Cortana can now be removed from a system.  I tested adding the following item to the AppxPackages.json and have been using it to remove it from my images.  There's also the new Windows Backup item being installed but I have not figure out how to remove it yet.

```
  {
    "AppxPackage": "Microsoft.549981C3F5F10",
    "VDIState": "Disabled",
    "URL": "???",
    "Description": "Microsoft Cortona"
  }  
```

**Comment by tmmuessig** [comment]
@brentil I'll work on getting this incorporated.  @robsmi-msfte  - Have you tested this yet?

I also know that with regards to Windows Backup, if I'm thinking of the same one, it is not supported to remove it from non-domain joined machines, but once its joined to a domain, windows removes it in the background.

**Comment by robsmi-msfte** [comment]
I have tested removing the first app, and it can be done in a supported manner.  You have the right app identified.

As for Windows Backup, I tried removing it in the past, but could not find a supported method.  But a quick search today, and found this, and credit "intowindows.com" organization for this solution:

https://www.intowindows.com/how-to-uninstall-windows-backup-app-from-windows-10-11/

I modified the code slightly to accommodate different package versions in case they exist:

Get-WindowsPackage -Online | Where PackageName -Match 'Microsoft-Windows-UserExperience-Desktop-Package' | Remove-WindowsPackage -Online

I can get those changes incorporated into a branch for testing.

**Comment by robsmi-msfte** [comment]
Regarding removing the Store app...the official word is [here](https://learn.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/cannot-remove-uninstall-or-reinstall-microsoft-store-app).
However, some customers operate in environments where the Store cannot reach the Internet, and so cannot update not only the Store app itself, but other apps.  Microsoft has been providing a "Store for Business", but that is being closed probably this year.
If we cannot update the Store app, or any other app, AND those apps show up in vulnerability reports, then we have no choice but to remove them.  I have tested and removing the Store app does not prevent any other existing Store apps from running.

Therefore I agree that we can at least add the entry for the Store app as well as 'Cortana' in 'AppxPackages.json', but like the other settings, we are leaving the 'VDIState' values to 'Unchanged'.

Thanks for reporting this.
