### ISSUE TITLE
Question About `Connected User Experiences and Telemetry Service`

### ISSUE THREAD

**Issue by aotongarcia** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#193]
I noticed that by default the script will disable `DiagTrack`, however, the Citrix Optimizer Tool has a note that disabling this service might prevent Microsoft Defender ATP from working correctly. I'm not sure where they are sourcing this information from but maybe you guys have a better reason for disabling it?

The only references I can find to this service in the Defender for Endpoint documentation is if you are using a proxy server. Any insight is greatly appreciated!

**Comment by robsmi-msfte** [comment]
We removed that entry from the code almost a year ago.
https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/pull/165

**Comment by aotongarcia** [comment]
@robsmi-msfte thanks for your response. I downloaded the latest release and this is still present there. Did you guys move away from doing releases and instead recommend doing a `git clone`?

**Comment by robsmi-msfte** [comment]
@aotongarcia  I think I know what's going on.  You probably downloaded the version marked 'latest'.  That actually is not up-to-date.  If you download from main, directly, for now, you should see that there is no 'DiagTrack' in any of the files.
We will get that fixed today.  Thanks for reporting that.

**Comment by robsmi-msfte** [comment]
Need to generate a new release.  We will incorporate the latest PRs into that first.

**Comment by aotongarcia** [comment]
I'll keep that in mind, thank you so much for all your hard work!
