### ISSUE TITLE
Incorrect Path In Multiple `PolicyRegSettings.json` policies

### ISSUE THREAD

**Issue by aotongarcia** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#194]
The following policies have an incorrect path in the JSON file when comparing what GPO actually sets:

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L290

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L402

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L437

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L444

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L451

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L458

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L465

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L472

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L479

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L486

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L507

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L514

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L521

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L528

https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/211628c081e7b59a64d4d6dab1c18bef303e8554/2009/ConfigurationFiles/PolicyRegSettings.json#L878

**Comment by robsmi-msfte** [comment]
We are reviewing your proposed changes at this time.  Thank you for your contribution.
