### ISSUE TITLE
Proposal to Include "DeleteUserAppContainersOnLogoff" Registry Key in Default Optimization

### ISSUE THREAD

**Issue by florian-ried** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#201]
Hi team,

I suggest adding the registry key "DeleteUserAppContainersOnLogoff" (DWORD, set to 1) to Default Optimization Tool. This key, located at HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy, addresses server slowdowns and unresponsiveness caused by the accumulation of excessive Windows firewall rules during multiple user sessions.

This optimization is already recommended by the Citrix Optimizer for similar issues, indicating its effectiveness. For reference, see the Microsoft support article (https://support.microsoft.com/en-gb/topic/march-26-2019-kb4490481-os-build-17763-402-c323e5c1-d524-dbdb-04a0-c3b5c8c8f2fd) and a relevant discussion on Spiceworks(https://community.spiceworks.com/topic/2285411-server2019-rds-hundreds-of-firewall-rules-per-user-per-session).

I'm curious if anyone has tested this in Windows 11 Multi-Session environments and can share their insights or if the problem is less prevalent there.

Thanks for considering this optimization to enhance performance.

BR 
Florian

**Comment by sp1nkick** [comment]
I would agree with this. We used to see this in RDS environments as users logged in and out, the rules list would get so long that logins/logoffs would get extremely slow.. Would have thought they have fixed this by now.

**Comment by ChristopherMahr** [comment]
i agree this was crucial for terminal services or citrix environments for logon and logoff speed.
if not set its kind of irriversible and would not help if you set it later. you need to delete millions of useless firewall rules to get rid of the problem.

**Comment by sp1nkick** [comment]
Do we know if this issue shows up on AVD setups as well?

**Comment by robsmi-msfte** [comment]
Hello,

I agree with this setting and have used it in production for months now to address the issue you mentioned @florian-ried.  I have not tested that setting on Windows 11 AVD.
I have created a branch, made the edit, and am putting in a PR for this setting now.  I will close this issue when that PR goes through to 'main'.
Thank you for submitting this enhancement to the VDOT tool.

Sincerely,

Robert M. Smith
