### ISSUE TITLE
QUESTION: Plans to disable/remove Win11 co-pilot

### ISSUE THREAD

**Issue by chbragg** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#206]
Is there any plans in the future to disable or remove the Windows 11 co-pilot or the Edge co-pilot?

**Comment by tmmuessig** [comment]
@chbragg  - I'm going to be honest, this is something we have not discussed between Robert and myself, and I've not looked for a supported way to remove it either.  Not saying it can't be removed, but it's not something that has been a priority at this point.

@robsmi-msfte - What are your thoughts?

**Comment by robsmi-msfte** [comment]
Hello,

We haven't looked at that yet, but there is a group policy setting.  I will add that to our backlog.  Thank you for the idea.

Thanks,

Robert M. Smith

**Comment by robsmi-msfte** [comment]
Would need to add this to "DefaultUserSettings.json", which I have done in a branch:

    {
        "HivePath": "HKLM:\\VDOT_TEMP\\Software\\SOFTWARE\\Policies\\Microsoft\\Windows\\WindowsCopilot",
        "KeyName": "TurnOffWindowsCopilot",
        "PropertyType": "DWORD",
        "PropertyValue": 1,
        "SetProperty": "False"
    }

I am going to set that to false by default.  That setting came from the Microsoft Windows 11 policy settings spreadsheet which is available on Microsoft.com.

**Comment by robsmi-msfte** [comment]
PR completed for this request.
#213
