### ISSUE TITLE
Want to revert/undo VDOT

### ISSUE THREAD

**Issue by MrBaas073** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#219]
Hi,

I want to revert/undo the VDOT scirpt i ran.
Is there any command to do this or is this a matter of changing everything back to enabled if you disabled it?

**Comment by tmmuessig** [comment]
Hi @MrBaas073 - There is no automated way to reverse the settings that were made from VDOT. The two options you have are to re-enable the settings manually, or rebuild the OS.
