### ISSUE TITLE
Azure VM Image Builder fails when using argument 'LGPO' as part of Optimizations parameter

### ISSUE THREAD

**Issue by andhri** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#221]
The documentation needs to be updated from accepting 'LGPO' as argument to 'LocalPolicy'.

![image](https://github.com/user-attachments/assets/647e1bb7-346f-4606-8acd-cb7daec4e24f)

**Comment by emaestrelli** [comment]
If you want to implement that you have to modify the line 557 of "Windows_VDOT.ps1" with:

If ($Optimizations -contains "LocalPolicy" -or $Optimizations -contains "All")

Then you can use the ".\Windows_VDOT.ps1 -Optimizations LocalPolicy –Verbose"

**Comment by jbass222** [comment]
Same issue as first reported in this thread. Any hope of a fix soon?

**Comment by tmmuessig** [comment]
This is fixed with #222 .  LGPO is no longer supported and LocalPolicy is utilized moving forward.
