### ISSUE TITLE
Get-Content command for APPX package isn't reading JSON correctly with where-object filter

### ISSUE THREAD

**Issue by ChrisAtFCPS** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#24]
When I run the one line to get-content where-object... VDIState -eq 'disabled' the $AppxPackage variable still ends up holding all lines and removing all applications? I had overwritten "Disabled" with "Enabled" on the apps that I wanted to remain but the conversion doesn't seem to read into the variable with the where filtered out...

**Comment by ChrisAtFCPS** [comment]
Found the issue... this command seemed to do the trick...

$AppxPackage = (Get-Content ...\AppxPackages.json | ConvertFrom-Json).Where({ $_.VDIState -eq 'Disabled' })

**Comment by tmmuessig** [comment]
Hi @ChrisAtFCPS  I just tried to duplicate this in my lab and was not able to reproduce your results.  When I change the VDIState in the AppxPackages.json to anything other thank ''Disabled' and then import with the below command I get the expected results that that package is not retained in the variable

`Get-Content ...\AppxPackages.json | ConvertFrom-Json | Where-Object { $_.VDIState -eq 'Disabled' }`

**Comment by ChrisAtFCPS** [comment]
Did you repro on Win10 20H2? Was it multi-session? I was using Win 10 Enterprise 20H2 no multi-session.

Sent from my iPhone

On Nov 18, 2020, at 8:03 AM, Tim <notifications@github.com> wrote:

﻿

Hi @ChrisAtFCPS<https://github.com/ChrisAtFCPS> I just tried to duplicate this in my lab and was not able to reproduce your results. When I change the VDIState in the AppxPackages.json to anything other thank ''Disabled' and then import with the below command I get the expected results that that package is not retained in the variable

Get-Content ...\AppxPackages.json | ConvertFrom-Json | Where-Object { $_.VDIState -eq 'Disabled' }

**Comment by tmmuessig** [comment]
I did it on Win10 2004 (no multi-session), but this is just a pure PowerShell command, and should not be dependent on the version of Win 10 at this point.

**Comment by ChrisAtFCPS** [comment]
I know it shouldn’t but I’m telling you what I saw… and it was just a plain vanilla, out of the box install of 20H2 and when I ran the command and then write the variable contents to the screen, all of the “enabled” entries for VDIState were in the list and ended up being removed. The only way to exclude them from the array was to change the command to the (XXX).Where{} notation.


jcl

**Comment by ChrisAtFCPS** [comment]
So when I run this command… and then enumerate the $AppxPackages, I see all entries:

$AppxPackage = Get-Content .\AppxPackages.json | ConvertFrom-Json | Where-Object { $_.VDIState -eq 'Disabled' }


When I split this into two lines, it runs properly and the $AppxPackage array contains only the disabled items:

$AppxPackage = Get-Content .\AppxPackages.json | ConvertFrom-Json
$AppxPackage = $AppxPackage | Where-Object { $_.VDIState -eq 'Disabled' }

Chris

**Comment by tmmuessig** [comment]
Chris  I was able to reproduce this issue and have fixed it in the 20H2 branch using your two separate lines. Can you give it a test? I have also updated all calls that were like this as I have a theory they were doing the same.

**Comment by ChrisAtFCPS** [comment]
Do you have any leads on why this functionality changed with 20H2? I will give it a try.

**Comment by tmmuessig** [comment]
This has been resolved and pushed to the master branch.  Please let us know if you have any more issues.
