### ISSUE TITLE
I cannot run the script

### ISSUE THREAD

**Issue by rafalstudnicki** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#25]
I cannot run the script.
I try as below:
My W10 version is 2004.

PS C:\Optimize> .\Win10_VirtualDesktop_Optimize.ps1 -WindowsVersion 2004
**Total Run Time: 0 Hours 0 Minutes 0 Seconds**
WARNING: A reboot is required for all changed to take effect

PS C:\Optimize> .\Win10_VirtualDesktop_Optimize.ps1
**Total Run Time: 0 Hours 0 Minutes 0 Seconds**
WARNING: A reboot is required for all changed to take effect

PS C:\Optimize>

**Comment by tmmuessig** [comment]
We have added a switch to the command which currently does not default to run everything

Please run the following.

Win10_VirtualDesktop_Optimize.ps1 -WindowsVersion 2004 -All

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rafalstudnicki** [comment]
Thx Tim, 
now works great
