### ISSUE TITLE
Script runs with no changes

### ISSUE THREAD

**Issue by tsrob50** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#27]
Hello,

Running the command outlined in the readme will not modify the OS.  It looks like the recently  updated Parameter block does not have  a default set.  Running .\Win10_VirtualDesktop_Optimize.ps1 -WindowsVersion 2004 -Verbose returns "Total Runtime 0 hours 0 minutes 0 seconds"  
Running .\Win10_VirtualDesktop_Optimize.ps1 -WindowsVersion 2004 -Verbose -All will run the script as expected with all configurations.

-Travis

**Comment by msft-jasonparker** [comment]
Hello @tsrob50 !
We updated the latest version of the script.  We are now evaluating the parameters and only running the tasks you specify.  If you don't specify any tasks, the script will execute all tasks.

Thanks for the feedback and be sure to let us know if you see any other issues.  I'll close this when you confirm its working from the latest version

Cheers,
VDI Team

**Comment by tsrob50** [comment]
It's working now.  Thanks!

**Comment by msft-jasonparker** [comment]
Confirmed working.
