### ISSUE TITLE
Removal of Appx Programs

### ISSUE THREAD

**Issue by johnyoakum** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#3]
I love this tool, but when I went to use it and then perform my sysprep after, I ran into an error. It turns out that this tool removes the appx packages that are provisioned for the machine, but if there are any user accounts, it doesn't remove the provisioning for the package, which causes sysprep to fail.

**Comment by sandude-ms** [comment]
Hello johnyoakum,

I have an idea of what is going on.  I am running some tests at this time and will report back with findings.

Thanks,

Robert Smith

**Comment by sandude-ms** [comment]
I tested two scenarios:

- Initial installation of Windows 10 Enterprise 2004, run optimization script, run Sysprep

- Initial installation of Windows 10 Enterprise 2004, run optimization script, apply all available updates, run Sysprep

I did not get a failure in either case.  Could you let me know the steps that I might be missing in my repro attempts?

**Comment by johnyoakum** [comment]
Did you build it in Hyper V or in Azure directly. I built the VM in Azure
with the windows 10 multi-session and Office 365 apps as my base. I
installed all the apps that I wanted to install for my host pool and then
also ran the optimization script which is where it failed. It may be due to
the Windows 10 Multi-session as the base.

*John Yoakum as the base*

University of Alaska Anchorage

Information Technology Services

Software Deployment Engineer

3211 Providence Dr, SSB 120

Anchorage, AK 99508

907-786-4922
jyoakum@alaska.edu

**Comment by sandude-ms** [comment]
I have tested in Hyper-V and in Azure.  Would you be able to run the optimization scripts after Sysprep, perhaps as a RunOnce activity?

**Comment by sandude-ms** [comment]
@johnyoakum, would you be able to run the optimization toolset after Sysprep?

**Comment by johnyoakum** [comment]
I would, except our leadership decided to shut down our WVD infrastructure for the time being and don’t want me to do anything with it due to costs.

John Yoakum
Software Deployment Engineer
University of Alaska Anchorage
3190 Alumni Dr
Anchorage, AK 99508
907-786-4922
________________________________
