### ISSUE TITLE
Re-install individual apps

### ISSUE THREAD

**Issue by Digiroka** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#30]
Hi all. hoping you can help me -

I used the 1909 script to remove apps, however we now require the 'Photos' app. I have tried to reinstall using the get-appxpackage and add-appxpackage command, however the photos app is not found.
There is no photo app within the c':\program files\windowsapps' folder.
I even tried via the windows store, but received a helpful 'something went wrong' error.

Any help greatly appreciated!

**Comment by tmmuessig** [comment]
Hi Digiroka,

If you look in the AppxPackages.json file for the Photos app, you should see a URL where you can reinstall the application from.  

The URL specifically for the Photos app is: https://www.microsoft.com/en-us/p/microsoft-photos/9wzdncrfjbh4?activetab=pivot:overviewtab

Does this help, or does this lead to the same error?

**Comment by Digiroka** [comment]
Hi - thank you for your quick reply. Unfortunately I receive a 'something went wrong' error when trying to install via the store.

**Comment by Digiroka** [comment]
I have resolved this - the Windows store service is disabled as part of the optimisation script. Enabling the service allowed me to install. Could this be added to the guidance? I can see quite a few situations where changes or new apps would be required, so detailing the required process would be useful. Thanks.
![image](https://user-images.githubusercontent.com/26280877/100450628-ebe41180-30ad-11eb-9f2c-c9d9ca455d09.png)

**Comment by tmmuessig** [comment]
Hi Digiroka,

You are absolutely correct and I have updated the readme to reflect these actions to be able to reinstall these packages.

**Comment by Digiroka** [comment]
hi @tmmuessig - I have hit another issue. You can't just download the store app as it doesn't provision for all users.
To provision for all users, you need to use add-appxprovisionedpackage, but to do that you need the full .appx package.
I'm going round in circles a bit here, do you have another method I could use to restore applications on the master image? TIA.
https://docs.microsoft.com/en-us/powershell/module/dism/add-appxprovisionedpackage?view=win10-ps

**Comment by robsmi-msfte** [comment]
Hello @Digiroka,

Check to see if the '**Microsoft Store Install Service**' service is disabled.  If so, set it to Manual, then try again.  You can control that service through the optimization scripts, or with Group Policy.  If you want to edit your optimization scripts, either delete this code block from 'Services.json':

`  {`
`    "Name": "InstallService",`
`    "VDIState": "Disabled",`
`    "Description": "Microsoft Store install service."`
`  },`

Or, within that code block, change the parameter 'VDIState' to anything other than "Disabled", such as "Unchanged".

Thanks,

Robert M. Smith

**Comment by Digiroka** [comment]
> Hello @Digiroka,
> 
> Check to see if the '**Microsoft Store Install Service**' service is disabled. If so, set it to Manual, then try again. You can control that service through the optimization scripts, or with Group Policy. If you want to edit your optimization scripts, either delete this code block from 'Services.json':
> 
> ` {`
> ` "Name": "InstallService",`
> ` "VDIState": "Disabled",`
> ` "Description": "Microsoft Store install service."`
> ` },`
> 
> Or, within that code block, change the parameter 'VDIState' to anything other than "Disabled", such as "Unchanged".
> 
> Thanks,
> 
> Robert M. Smith

Hi Robert - thanks for your reply, but I already started the app install service (please see post above)
https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/issues/30#issuecomment-734817275
