### ISSUE TITLE
DefaultUserSettings.txt for 2004 not used

### ISSUE THREAD

**Issue by bitdeft** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#32]
Looking here:
https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/blob/master/2004/ConfigurationFiles/DefaultUserSettings.txt

The "DefaultUserSettings.txt" File doesn't seem to be used anywhere. In Win10_VirtualDesktop_Optimize.ps1 I can't see a reference to it at all. it is only looking for the .json file. When using Build_JSON_Files.ps1 (though I figure that ps script is out-of-date at this point, it was only in initial code migration, no changes since), the defaultusersettings file is output as a .txt, not a JSON. So the JSON is missing when Win10_VirtualDesktop_Optimize.ps1 is run.

Is this file just there for reference? This file is also in the 1909 directory as well.

**Comment by tmmuessig** [comment]
Hi @bitdeft 

The defaultusers.txt is still there but you are right, it is currently not being called. @msft-jasonparker made some upgrades and converted it to json. 

You are also correct in that the Build_json files scrip is out of date and has not been updated to reflect the change. 

It is on the list to be updated as soon as possible.
