### ISSUE TITLE
20H2: PreventNetworkTrafficPreUserSignIn GPO setting prevents OneDrive from automatically starting

### ISSUE THREAD

**Issue by MrR0bert** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#37]
During testing, we have found that the following setting prevents OneDrive from starting automatically, even after the first time starting it manually:

Computer
SOFTWARE\Microsoft\OneDrive
PreventNetworkTrafficPreUserSignIn
DWORD:1

For a smoother user experience, we have removed this setting to allow OneDrive to start automatically when users sign in to the session hosts.

**Comment by robsmi-msfte** [comment]
Hello @MrR0bert,

We will make a note of that in the Readme.  If the issue gets more weight overall, we will revert that setting to default.  Thank you for reporting that.

Sincerely,

Robert Smith

**Comment by sandude-ms** [comment]
Hello @MrR0bert,

I changed the default for the OneDrive setting in the LGPO files, for '2009' (20H2).  I also made a note of that in the Readme.  I tested before and after, confirming that the OneDrive setting remains unchanged.  I also tested applying the full package to a test machine, which also confirmed the setting remains unchanged.

Thank you again for reporting that.  If you get a chance, please test this and let us know how it goes.

Thanks,

Robert Smith

**Comment by MrR0bert** [comment]
We modified this entry in our custom 'version' (a copy of the '2009') and this indeed makes OneDrive start automatically again.

Thanks!
