### ISSUE TITLE
OneDrive sync causes Office apps to hang (Not Responding)

### ISSUE THREAD

**Issue by nippertje** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#38]
We use this script in our standard build for WVD and came across a very subtle problem with OneDrive and Office apps. When OneDrive is syncing with a library of several thousand files, Office apps will hang for several seconds, every 10-20 seconds. This cycle continues until the sync is completed. It first came to light when we started connecting customer's Sharepoint document libraries into OneDrive.

This can easily be reproduced by signing in as a user, open a few Office documents from the library and then hitting Save on one, which kicks off a OneDrive sync.

We are pretty certain that the issue is caused by one of the optimisations, but cannot pinpoint which one. We have deduced this by adding a session host to the pool with a marketplace image, signing in with the same user profile and repeating the test.

Do you have any idea which settings we could eliminate or tune to try to resolve this?

**Comment by nippertje** [comment]
![officehang](https://user-images.githubusercontent.com/74324474/105920991-3511fc80-6030-11eb-820c-e8d9c1542a95.png)
Just dropping here a screengrab of how this looks on the affected Session Host.

**Comment by robsmi-msfte** [comment]
Hello @nippertje,

We do very little that should affect OneDrive.  There is one local policy setting directly related to OneDrive that we set:

\Windows Components\OneDrive
"Prevent OneDrive from generating network traffic until the user signs in to OneDrive"
State: Disabled

I would like to know a few additional details:

- Version of Windows 10
- How recently the optimization tool was downloaded.
- Have you applied any updates to the session hosts?
- What version of OneDrive.exe is on your session host

You might try:

- Check if there are any available updates for Office
- Check if there are any available updates for Windows, though this could depend on your update strategy.  This may not be an option.

Thanks,

Robert Smith

**Comment by sandude-ms** [comment]
Hello @nippertje,

I made a change to a OneDrive setting and merge that into the "master" branch.  If not too much trouble, try that on a new session host and let me know if it helps.  I documented this change in the Readme.

Thanks,

Robert M. Smith

**Comment by nippertje** [comment]
Hi Robert - Thanks for taking the time to check this out. Sorry that this issue is so vague, but there is very little to go on and we hit upon the fact that we can so easily reproduce it on an optimised SH image but can;t on a non-optimised one. 

We are running this version of Win 10 on both optimised and marketplace images
![image](https://user-images.githubusercontent.com/74324474/106047421-81664680-60db-11eb-9c60-98b01b5d716c.png)

basically, we take the same gallery image as the starting point, but the optimised one we do the following with:
- install Adobe DC Reader
- Teams machine-wide installer
- install UK lang pack
- install an endpoint security remote agent (only the remote agent that talks to the remote console, no protection agent at all yet)
- update to new Edge
- run updates until only 20H2 is offered
- run the optimisation script

OneDrive is the following on both SH
![image](https://user-images.githubusercontent.com/74324474/106047830-00f41580-60dc-11eb-9246-32e98268aa63.png)

Windows updates are run and re-run to completion on both optimised and marketplace, only ignoring the 20H2 update. Updating the image prior to capture then setting policy to download only is our strategy for now.

I am working with an optimisation script from around early December. It is possible there have been changes and I note the new master you have posted, so I will try that tomorrow during UK business hours.

**Comment by sandude-ms** [comment]
We have made changes, but recently only to the 20H2 (2009) branch.  If you have time, download the entire current repository, extract it to a test machine, then run this:

`Win10_VirtualDesktop_Optimize.ps1 -WindowsVersion 2009 -Verbose`

The OneDrive change I made today should be applied to your machine then.  If you can determine if this resolves the issue, we can go from there.  Note that you can run this tool with the '2009' parameter just fine on 2004.

**Comment by nippertje** [comment]
OK, so here is an update. I don't think changes in the Optimiser script necessarily caused the issue. It was just much easier to reproduce with an optimised image (perhaps because it is leaner and faster). We were able to get Office app to hang on OneDrive syncing against a large library but just not as often or reliably.

The goods news is that we fresh, optimised image of 20H2 (2009) with exactly our same build process and using the latest master is holding up well in production. Users have reported not incidents of Office apps hanging for around 24 hours so its looking good.

**Comment by robsmi-msfte** [comment]
That is great news.  Let us know if things change.
