### ISSUE TITLE
AppX Cleanup For Existing Users

### ISSUE THREAD

**Issue by Roger-Elmer** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#4]
After running the script, there are numerous leftover broken shortcuts in existing user profiles for the AppX packages that were removed. An example of this can be seen in this post.

https://techcommunity.microsoft.com/t5/windows-virtual-desktop/windows-virtual-desktop-optimization-tool-now-available/m-p/1560074/highlight/true#M5070

Can something be added to the script to clean this up or is there something that we can do?

**Comment by robsmi-msfte** [comment]
I was testing this issue, and ran across a problem in the Appx section of the PowerShell code.

This is what was there:

    {
        $Package = "*$($Item.AppxPackage)*"
        Write-Verbose "Attempting to remove $($Item.AppxPackage) - $($Item.Description)"
        Get-AppxPackage -Name $Package | Remove-AppxPackage -ErrorAction SilentlyContinue  | Out-Null
        
        #Write-Verbose "`t`tAttempting to remove [All Users] $($Item.AppxPackage) - $($Item.Description)"
        #Get-AppxPackage -AllUsers -Name $Package | Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue 
        
        Write-Verbose "`t`tRemoving Provisioned Package $($item.AppxPackage)"
        Get-AppxProvisionedPackage -Online | Where-Object { $_.PackageName -like $Package } | Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue | Out-Null
    }

This is what it is supposed to be:

    {
        $Package = "*$($Item.AppxPackage)*"
        Write-Verbose "Attempting to remove $($Item.AppxPackage) - $($Item.Description)"
        Get-AppxPackage -Name $Package | Remove-AppxPackage -ErrorAction SilentlyContinue  | Out-Null
        
        Write-Verbose "Attempting to remove [All Users] $($Item.AppxPackage) - $($Item.Description)"
        Get-AppxPackage -AllUsers -Name $Package | Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinue 
        
        Write-Verbose "Removing Provisioned Package $($item.AppxPackage)"
        Get-AppxProvisionedPackage -Online | Where-Object { $_.PackageName -like $Package } | Remove-AppxProvisionedPackage -Online -ErrorAction SilentlyContinue | Out-Null
    }

I am currently checking in the correct code.  Could you check your local copy of the PowerShell script and edit as I have here and test again?  The issue could be that if the "Remove-AppxPackage -AllUsers" command did not run, the user's profile will not be correctly scrubbed of removed apps when they next log in.  You can run the entire script again and it won't change anything, other than what we fix here.

**Comment by Roger-Elmer** [comment]
Doesn't look like that is working. I get the following error when using the updated code for each of the apps that it tries to remove.

Removing Provisioned Package Microsoft.MixedReality.Portal
Attempting to remove Microsoft.SkypeApp - Instant message, voice or video call app
Attempting to remove [All Users] Microsoft.SkypeApp - Instant message, voice or video call app
Remove-AppxPackage : Removal failed. Please contact your software vendor.
Deployment Remove operation with target volume C: on Package Microsoft.SkypeApp_15.63.76.0_x86__kzf8qxf38zg5c from:
failed with error 0x80070002. See http://go.microsoft.com/fwlink/?LinkId=235160 for help diagnosing app deployment
issues.
At C:\users\RElmer\Desktop\RemoveAppxPackages.ps1:24 char:52
+ ...  $Package | Remove-AppxPackage -AllUsers -ErrorAction SilentlyContinu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Remove-AppxPackage], COMException
    + FullyQualifiedErrorId : System.Runtime.InteropServices.COMException,Microsoft.Windows.Appx.PackageManager.Comman
   ds.RemoveAppxPackageCommand

Removing Provisioned Package Microsoft.SkypeApp

**Comment by Roger-Elmer** [comment]
So I ran it a second time and oddly didn't get any error messages. However, it did not do anything to clean up the remnants leftover in other existing user profiles unfortunately.

**Comment by sandude-ms** [comment]
- How are the profiles being managed? (on each device, roaming, FSLogix, other?)

I tested yesterday and was not able to see those problems.  I installed Windows 10 2004 Enterprise, I applied all available updated including the latest CU.  I created a test user and logged in so that profile would be created.  I then logged off, logged on as another user, ran the script, rebooted, and found that the test user's Start Menu was clean with no broken links.  The PowerShell command that removes packages for "AllUsers" I believe,

The list of apps that can be removed by the script are in that list because those are the ones that can be removed in a supported method.  What we might want to do is shorten that list, or even try not removing any of the UWP apps.  You could easily accomplish that by deleting the configuration file 'AppxPackages.json'.

And I have an idea of what might be happening with the error message you posted, because I noticed that in my environment also.  From the PowerShell output before and after running the optimizations.

**Comment by Roger-Elmer** [comment]
I'm using FSLogix for the profile management.

Prior to my testing yesterday I had already trimmed down the powershell script to only run the part that removes the apps and I had trimmed down the AppxPackages.json file to only attempt to remove two apps. I did this because I had recently re-dployed my host pools since I was having other problems related to the optimization script as well.

In my testing I've tried running the script as an admin user while the other affected user is logged on and also while logged off and saw no difference in the cleanup of the broken start menu links. In fact, with the Skype app, I found that it didn't even get removed from the admin user that ran the script unlike the other app that removed successfully. The app itself is uninstalled but an entry for it remains in the start menu and is only missing the icon.

![image](https://user-images.githubusercontent.com/69128261/90293632-63f93500-de39-11ea-9e77-10947180c15a.png)

**Comment by sandude-ms** [comment]
@Roger-Elmer you might try bringing up Task Manager while logged on as that user, then ending the process 'StartMenuExperienceHost.exe'.  This might force Windows to rebuild the Start Menu elements for that user.

**Comment by Roger-Elmer** [comment]
@sandude-ms thanks for the tip but that did not work either.

**Comment by sandude-ms** [comment]
I believe I found a much easier way.  You can create a batch file that a normal user can run, and should reset the Start Menu.  What you can do is save the following to a batch file:

`start /wait taskkill /IM StartMenuExperienceHost.exe /F`
`rd /S /Q "%UserProfile%\Appdata\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\AC"`
`rd /S /Q "%UserProfile%\Appdata\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\AppData"`
`rd /S /Q "%UserProfile%\Appdata\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalCache"`
`rd /S /Q "%UserProfile%\Appdata\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\LocalState"`
`rd /S /Q "%UserProfile%\Appdata\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\RoamingState"`
`rd /S /Q "%UserProfile%\Appdata\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\Settings"`
`rd /S /Q "%UserProfile%\Appdata\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\SystemAppData"`
`rd /S /Q "%UserProfile%\Appdata\Local\Packages\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\TempState"`
`Start C:\Windows\SystemApps\Microsoft.Windows.StartMenuExperienceHost_cw5n1h2txyewy\StartMenuExperienceHost.exe`

I added the last line to try to get the Start Menu process running again, so it would rebuild the local cache.  Depending on how soon you click the Start Menu after this reset, you might get an error saying there's something wrong with the Start Menu and to sign out.  I found that if you wait a short time before clicking the Start Menu, you won't get an error.
An interesting note on this process...it won't wipe out user pinned Start Menu items.

**Comment by Roger-Elmer** [comment]
That worked perfectly! Sorry I didn't get back to you sooner with the manual steps you outlined. I ran into some permission errors when trying to do it and didn't have the time to figure that out and update you. This works even better!

**Comment by sandude-ms** [comment]
Glad it worked!  Hopefully a sanctioned fix can be incorporated in to future builds.  But in the meantime, I have found no downside with this method.  Thanks for reporting this and have a great deployment.
