### ISSUE TITLE
Not a issue but a quastion?

### ISSUE THREAD

**Issue by rstolpe** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#44]
Hi,
I'm wondering if this is in HEX or decimal?
        "HivePath": "HKLM:\\System\\CurrentControlSet\\Services\\LanmanWorkstation\\Parameters\\",
        "Keys": [
            {
                "Name": "DisableBandwidthThrottling",
                "PropertyType": "DWORD",
                "PropertyValue": 1,
                "SetProperty": "True"
            },

**Comment by aaronparker** [comment]
Decimal; however `1` in Hex is `1` in Decimal
