### ISSUE TITLE
Outlook client disconnected

### ISSUE THREAD

**Issue by davetustin** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#82]
Hi,

I am using the VDI Optimization Script on Windows 10 20H2 and using the 2009 flavour. For some reason the script has caused the Outlook client to disconnect from the Exchange server. Please see the before and after screenshots.

To test it I did the following.

1. Tested Outlook on a clean build (successful)
2. Ran the VDI Optimization Script
3. Tested Outlook again (failed)
4. Restored the clean build from backup
5. Tested Outlook again (successful)

To make this more complicated, I have used this script before with success. Although I have had it failed which was resolved by doing a rebuild of the image.

I am now able to replicate it and can confirm that it appears the script is causing it and I have no idea why, as yet. 

Now I know the script can cause it, I will drill further down into it, but wanted to raise it on here in case anyone might know.

Thanks
Dave

![successful](https://user-images.githubusercontent.com/46324811/119677505-b0e15180-be36-11eb-953f-0866253768f9.png)
![failed](https://user-images.githubusercontent.com/46324811/119677513-b179e800-be36-11eb-8385-28e69db49910.png)

**Comment by sandude-ms** [comment]
Hello @davetustin. If you downloaded the VDOT tool recently, there should be a new event log in your Windows Event Viewer under "Applications and Services Logs", called "Virtual Desktop Optimization".  You could start by going through that and see if there are any errors.
The way that we usually troubleshoot is to get a base image, perhaps in Hyper-V, do an initial install, then snapshot that.  The idea is so you can roll back in seconds and iterate testing.  Using the 50/50 approach, only apply say 3 categories of optimizations and note the result.  We are trying to narrow down if we can, which category of optimizations are causing the issue.  If you can find this out, let us know and we can start from there.

One thing you might look at is local policy settings, and specifically this setting:

    {
        "RegItemPath": "HKLM:\\SOFTWARE\\Policies\\Microsoft\\Windows\\NetworkConnectivityStatusIndicator",
        "RegItemValueName": "DisablePassivePolling",
        "RegItemValueType": "DWord",
        "RegItemValue": "1",
        "VDIState": "Enabled"
    },

Try changing your copy of 'PolicyRegSettings.json" by changing the 'VDIState' value from "Enabled" to "Unchanged".  If that resolves the issue, let us know.

**Comment by davetustin** [comment]
Thanks for the info!

I changed the VDIState for NetworkConnectivityStatusIndicator to Unchanged and that looks to have resolved it.

Re-running the script with the VDIState for NetworkConnectivityStatusIndicator set to Enabled, broke it again.

Changing the value in the registry for DisablePassivePolling from 1 to 0 manually, also fixed it.

I really appreciate your help on this, I thought this was going to be a nightmare to get to the bottom of!

Cheers
Dave
