### ISSUE TITLE
Error when running from AIB

### ISSUE THREAD

**Issue by ii-batman** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#85]
Hi - Running the Azure Image Build task, added the script and folders to my cust folder and running that from the task, logs show error when running the scrtip:

> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: AIB Customization: - Notepad-plus-plus-8.0x64 Installation - Completed
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: AIB Customization: - DeprovisioningScript.ps1 - Start
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: VERBOSE: Performing the operation "Set Content" on target "Path: C:\DeprovisioningScript.ps1".
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: VERBOSE: Performing the operation "Clear Content" on target "Item: C:\DeprovisioningScript.ps1".
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: AIB Customization: - DeprovisioningScript.ps1 - End
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: AIB W10_optimisations script - start
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: [VDI Optimize] Disable / Remove Windows Media Player
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: [VDI Optimize] Removing Appx Packages
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: [VDI Optimize] Disable Scheduled Tasks
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: [VDI Optimize] Set Default User Settings
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: [VDI Optimize] Disable Autologgers
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: [VDI Optimize] Disable Services
**> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT ==> azure-arm: ERROR: Access is denied.**
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: [VDI Optimize] Configure LanManWorkstation Settings
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: New HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\ -Name DisableBandwidthThrottling -Value 1
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: New HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\ -Name FileInfoCacheEntriesMax -Value 1024
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: New HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\ -Name DirectoryCacheEntriesMax -Value 1024
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: New HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\ -Name FileNotFoundCacheEntriesMax -Value 1024
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: New HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters\ -Name DormantFileLimit -Value 256
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT     azure-arm: [VDI Optimize] Configuring Network Adapter Buffer Size
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 packer-builder-azure-arm plugin: [INFO] command 'powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-60bf3f01-163b-474a-3f32-f1e90741bfbe.ps1; &'c:/Windows/Temp/script-60bf3f01-e68f-b5e1-ed1e-85949d3c819f.ps1'; exit $LastExitCode }"' exited with code: 16001
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT ==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 packer-builder-azure-arm plugin: [INFO] RPC endpoint: Communicator ended with: 16001
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT ==> azure-arm: 
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 [INFO] 3321 bytes written for 'stdout'
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT ==> azure-arm: The resource group was not created by Packer, deleting individual resources ...
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 [INFO] 27 bytes written for 'stderr'
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 [INFO] RPC client: Communicator ended with: 16001
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 [INFO] RPC endpoint: Communicator ended with: 16001
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 packer-provisioner-powershell plugin: [INFO] 3321 bytes written for 'stdout'
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 [INFO] (telemetry) ending powershell
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER OUT ==> azure-arm:  -> Microsoft.Compute/virtualMachines : 'pkrvmq5k9masxzl'
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 packer-provisioner-powershell plugin: [INFO] 27 bytes written for 'stderr'
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 packer-provisioner-powershell plugin: [INFO] RPC client: Communicator ended with: 16001
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR 2021/06/08 10:22:35 packer-provisioner-powershell plugin: c:/Windows/Temp/script-60bf3f01-e68f-b5e1-ed1e-85949d3c819f.ps1 returned with exit code 16001
> [a02cac9a-5c2a-46f3-94ad-a429302808fd] PACKER ERR ==> azure-arm: The resource group was not created by Packer, deleting individual resources ...

The script runs fine interactively but not from IAM, is there a way around this? what do you suggest?
Thanks Everyone!

**Comment by ii-batman** [comment]
I am having trouble running the script from Azure Image builder.
I am uploading to my Azure Repo the zip file and a script to unzip the zip file, and run Win10_VirtualDesktop_Optimize.ps1
On the packer logs I can see that the exit code is 16000 when it's expecting error code 0
Is there a special way to incorporate the script with AIB.DevOps?
Thanks

**Comment by KenBenjamin** [comment]
@ii-batman , #87 should fix your issue. Give it a try and maybe comment on the PR if it does/doesn't work.

**Comment by ii-batman** [comment]
@KenBenjamin, sorry mate, I am new to this... where is the script to test?

**Comment by KenBenjamin** [comment]
@ii-batman You might look at what options there are in Packer to deal with warnings vs. errors. That service that can't stop should report as a warning, not an error. Maybe you have it set to fail on warnings? Not a Packer user so I can't say. It could also be something in my code but I'm not seeing it and I have services that can't stop, too.

Alternatively, you may want to fork the repo and tweak the `Services.json` file to avoid trying to stop services that can't be stopped in your configuration. I'd recommend forking it anyhow so you can configure you're own options in various areas.

**Comment by ii-batman** [comment]
> @KenBenjamin @tmmuessig 
Hi Everyone, 
I am able to run the script via AIB but still getting errors:

> >T     azure-arm: VERBOSE: Attempting to disable Scheduled Task: Consolidator
> T ==> azure-arm: ERROR: Access is denied.
> T     azure-arm: VERBOSE: Attempting to disable Scheduled Task: Diagnostics
> T     azure-arm: VERBOSE: Attempting to disable Scheduled Task: FamilySafetyMonitor
> T     azure-arm: VERBOSE: Attempting to disable Scheduled Task: FamilySafetyRefreshTask
> T     azure-arm: VERBOSE: Attempting to disable Scheduled Task: MapsToastTask
> T     azure-arm: VERBOSE: Attempting to disable Scheduled Task: Microsoft Compatibility Appraiser
> .........
>  PACKER OUT     azure-arm: Thank you from the Virtual Desktop Optimization Team
>  PACKER OUT     azure-arm: Done Optim with exit code 1
>  PACKER OUT     azure-arm: AIB Customization: - DeprovisioningScript.ps1 - Start
>  PACKER OUT     azure-arm: VERBOSE: Performing the operation "Set Content" on target "Path: C:\DeprovisioningScript.ps1".
>  PACKER OUT     azure-arm: VERBOSE: Performing the operation "Clear Content" on target "Item: C:\DeprovisioningScript.ps1".
>  PACKER OUT     azure-arm: Write-Output '>>> Waiting for GA Service (RdAgent) to start ...' while ((Get-Service RdAgent).Status -ne 'Running') { Start-Sleep -s 5 } Write-Output '>>> Waiting for GA Service (WindowsAzureTelemetryService) to start ...' while ((Get-Service WindowsAzureTelemetryService) -and ((Get-Service WindowsAzureTelemetryService).Status -ne 'Running')) { Start-Sleep -s 5 } Write-Output '>>> Waiting for GA Service (WindowsAzureGuestAgent) to start ...' while ((Get-Service WindowsAzureGuestAgent).Status -ne 'Running') { Start-Sleep -s 5 } Write-Output '>>> Sysprepping VM ...' if( Test-Path $Env:SystemRoot\system32\Sysprep\unattend.xml ) {   Remove-Item $Env:SystemRoot\system32\Sysprep\unattend.xml -Force } & $Env:SystemRoot\System32\Sysprep\Sysprep.exe /oobe /generalize /quiet /quit /mode:vm while($true) {   $imageState = (Get-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Setup\State).ImageState   Write-Output $imageState   if ($imageState -eq 'IMAGE_STATE_GENERALIZE_RESEAL_TO_OOBE') { break }   Start-Sleep -s 5 } Write-Output '>>> Sysprep complete ...'
>  PACKER OUT     azure-arm: AIB Customization: - DeprovisioningScript.ps1 - End
>  PACKER ERR 2021/06/16 09:02:08 packer-builder-azure-arm plugin: [INFO] command 'powershell -executionpolicy bypass "& { if (Test-Path variable:global:ProgressPreference){set-variable -name variable:global:ProgressPreference -value 'SilentlyContinue'};. c:/Windows/Temp/packer-ps-env-vars-60c9bbb1-7ce5-5d8e-aab8-5259cd6ba417.ps1; &'c:/Windows/Temp/script-60c9bbb1-59c0-8bf2-4514-89f6864e8e1f.ps1'; exit $LastExitCode }"' exited with code: 1
>  PACKER OUT ==> azure-arm: Provisioning step had errors: Running the cleanup provisioner, if present...
>  PACKER ERR 2021/06/16 09:02:08 packer-builder-azure-arm plugin: [INFO] RPC endpoint: Communicator ended with: 1
> --------------------------
> 
> >  PA PACKER OUT ==> azure-arm: The resource group was not created by Packer, not deleting ...
>  PACKER ERR 2021/06/16 09:04:51 [INFO] (telemetry) ending azure-arm
>  PACKER OUT Build 'azure-arm' errored after 12 minutes 50 seconds: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
>  PACKER ERR ==> Wait completed after 12 minutes 50 seconds
>  PACKER OUT 
>  PACKER ERR 2021/06/16 09:04:51 machine readable: error-count []string{"1"}
>  PACKER OUT ==> Wait completed after 12 minutes 50 seconds
>  PACKER ERR ==> Some builds didn't complete successfully and had errors:
>  PACKER OUT 
>  PACKER ERR 2021/06/16 09:04:51 machine readable: azure-arm,error []string{"Script exited with non-zero exit status: 1.Allowed exit codes are: [0]"}
>  PACKER OUT ==> Some builds didn't complete successfully and had errors:
>  PACKER ERR ==> Builds finished but no artifacts were created.
>  PACKER OUT --> azure-arm: Script exited with non-zero exit status: 1.Allowed exit codes are: [0]
> > 


I tried editing the json to remove the sched task but it just fails on another...
Any help will be greatly appreciated.
Thanks

**Comment by KenBenjamin** [comment]
@ii-batman You need to change the config for each of the services that can't be disabled. It looks like you got the power management one but not the consolidator. Please post your Services.json if you need more help and I can take a look.

**Comment by ii-batman** [comment]
@KenBenjamin 
I removed the sched tasks completely now fails on User settings... there is something that is failing which I cannot put my finger on!
Would really appreciate  @tmmuessig  help please?

**Comment by KenBenjamin** [comment]
You could try editing my patch to remove all Write-Error / Write-Warnings and see if that doesn't fix it for you. If so, that's a worthwhile change for the team to consider as part of integrating my patch, assuming they choose to do so.

**Comment by ii-batman** [comment]
@tmmuessig @KenBenjamin @jeffstokes72 
Right guys, I have identified that the error is always on the defaultusersettings region.
Without this region the build finishes fine.
Last error:
`     azure-arm: AIB Customization: Finished OS Optimizations script
     azure-arm: [VDI Optimize] Set Default User Settings
     azure-arm: @{HivePath=HKLM:\VDOT_TEMP\Software\Microsoft\Windows\CurrentVersion\Explorer; KeyName=ShellState; PropertyType=BINARY; PropertyValue=0x24,0x00,0x00,0x00,0x3C,0x28,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00; SetProperty=True}
     azure-arm: @{HivePath=HKLM:\VDOT_TEMP\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced; KeyName=IconsOnly; PropertyType=DWORD; PropertyValue=1; SetProperty=True}
 ==> azure-arm: ERROR: Access is denied.
     azure-arm: @{HivePath=HKLM:\VDOT_TEMP\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced; KeyName=ListviewAlphaSelect; PropertyType=DWORD; PropertyValue=0; SetProperty=True}
     azure-arm: @{HivePath=HKLM:\VDOT_TEMP\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced; KeyName=ListviewShadow; PropertyType=DWORD; PropertyValue=0; SetProperty=True}
`

Thanks guys...

**Comment by KenBenjamin** [comment]
Okay, so go into DefaultUserSettings.json and remove the offending registry entry.

**Comment by ii-batman** [comment]
> Okay, so go into DefaultUserSettings.json and remove the offending registry entry.

Don't think the problem is on the settings.json. The error comes way before the ForEach section and somethings before the first IF statement. I even thought it was a regload related error. Tweeked that part of the script so much... ran over 60 releases... all failed!!! Would be great to have the @tmmuessig input... 😃

**Comment by ii-batman** [comment]
https://github.com/The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool/issues/70#issuecomment-865409154 
The above thread resolved me issue.
Thanks for the script guys! Hope you are still working on the 21H1 update?
Bless!
