### ISSUE TITLE
Build_JSON_Files.ps1

### ISSUE THREAD

**Issue by vi3art90** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#88]
Hello. Can't understand what the Build_JSON_Files.ps1 script file is for?

**Comment by tmmuessig** [comment]
Hi @vi3art90, 

I have to be honest, I either need to update it, or completely remove it as we have other ways we are creating/updating the existing files moving forward.  We used that initially to build the JSON files when we converted them from txt files.  As of right now it is completely outdated for about half of the JSON files we have created. 

It is not needed to be able to run the script to optimize your VM's.
