### ISSUE TITLE
Set-ExecutionPolicy

### ISSUE THREAD

**Issue by rafalstudnicki** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#90]
Hi, how can I run this script?

Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Force -Verbose
.\Win10_VirtualDesktop_Optimize.ps1 -WindowsVersion 2009 -Restart -Verbose

![image](https://user-images.githubusercontent.com/25172299/124353785-d8cb8e00-dc08-11eb-9d73-cde41035586a.png)

**Comment by tmmuessig** [comment]
Make sure you are running as administrator and then run the set-executionPolicy all by itself and then run the ps1

**Comment by sandude-ms** [comment]
Also, you can set the ExecutionPolicy only for duration of the current process by running:

Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope LocalMachine -Force

**Comment by sandude-ms** [comment]
My apologies...I meant this:

Set-ExecutionPolicy -ExecutionPolicy RemoteSigned **-Scope Process**

https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.security/set-executionpolicy?view=powershell-7.1
