### ISSUE TITLE
Contact Search in outlook not working?

### ISSUE THREAD

**Issue by coding-totoro** [The-Virtual-Desktop-Team/Virtual-Desktop-Optimization-Tool#91]
Regular search in inbox works, but contract search in contact folder does not work. 

21H1, ran with -2009 parameters, and minor edits to keep snipping tool in and calculator.

**Comment by tmmuessig** [comment]
Understandable, the configurations we provide are just recommendations.  Modifying them is expected to suit the needs of each organization.
